### PR TITLE
Recursive breadcrumbs

### PR DESCRIPTION
**Pull request by yajo**
Previously, shop category breadcrumbs only showed "Shop / Current category".

This recursive template shows **all** breadcrumbs.

CC @dgzurita @rafaelbn @antespi.

### CODE REVIEW

**Comment by rafaelbn** [comment]
Tested in runbot :+1: very nice

**Comment by antespi** [comment]
:+1: tested in runbot

**Comment by rafaelbn** [comment]
Please @Yajo resolve conflicts, thanks

**Comment by antespi** [comment]
@Yajo I think doing a rebase you'll get the conflict

**Comment by yajo** [comment]
Should be fixed.

**Comment by dgzurita** [comment]
:+1: tested in runbot

**Pull request merged**
