### PR TITLE
[14.0][MIG] website_sale_product_item_cart_custom_qty: Migration to 14.0

### PR DESCRIPTION
**Pull request by Aldeigja**
Standard migration

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional review ok!

**Review by geomer198 — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@OCA/e-commerce-maintainers good for merge?

**Comment by francesco-ooops** [comment]
@simahawk would it be possible to merge the migration? we need to open a PR to fix an incorrect behavior on mobile

Thanks :)

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
