### PR TITLE
[DEL][9.0] Delete moved modules to OCA/sale-workflow

### PR DESCRIPTION
**Pull request by SodexisTeam**
These modules were moved to OCA/sale-workflow.
- sale_automatic_workflow
- sale_automatic_workflow_exception
- sale_payment_method
- sale_payment_method_automatic_workflow
- sale_payment_method_transaction_id
- sale_quick_payment

Also, it seems to be confusing to have these modules available in OCA/e-commerce & OCA/sale-workflow(8.0 branch).

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by gurneyalex** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Comment by gurneyalex** [comment]
@guewen this deserves an announce on the contributors mailing list.

**Comment by guewen** [comment]
@gurneyalex Not sure it's worth because those modules have been removed from the 8.0 branch a while ago. These are just remnants due to the lag between 8.0 and 9.0.

**Comment by gurneyalex** [comment]
ok

**Pull request merged**
