### PR TITLE
[15.0][MIG] website_sale_b2x_alt_price: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36596

please @Tardo @victoralmau  review this

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]
Functional review OK.

**Comment by kimasplund** [comment]
any chance of getting the v15 module?

**Comment by pedrobaeza** [comment]
Please review this PR to get it merged: https://odoo-community.org/resources/review

**Review by chienandalu — APPROVED** [review]
Code and functional review :+1:

**Pull request merged**
