### PR TITLE
[14.0][MIG] website_sale_suggest_create_account: Migration to 14.0

### PR DESCRIPTION
**Pull request by sebasdrk17**
website_sale_suggest_create_account: Migration to 14.0

### CODE REVIEW

**Comment by sebasdrk17** [comment]
Hello @oscarolar and @hugho-ad could you review please?

cc @luisg123v

**Comment by francesco-ooops** [comment]
@sebasdrk17 can you rebase?

**Comment by francesco-ooops** [comment]
@OCA/e-commerce-maintainers can you rebase in order to test runboat? thanks!

**Comment by houssine78** [comment]
Hi @pedrobaeza i think that now the psc member can run a commande to automatically rebase the PR ? If so is it possible for you to rebase this PR as https://github.com/OCA/e-commerce/pull/464 is waiting for this one to be merged.

thank you

**Comment by pedrobaeza** [comment]
The command can't be executed over organization branches

**Comment by houssine78** [comment]
ok i'll ping the author of the PR. Thank you anyway.

**Comment by houssine78** [comment]
@sebasdrk17 could you please rebase your PR ?

**Review by houssine78 — APPROVED** [review]
LGTM

**Comment by luisg123v** [comment]
@houssine78 rebase performed.

Regards,

**Comment by houssine78** [comment]
@pedrobaeza all is green ! I think is ready to be merged

**Comment by pedrobaeza** [comment]
A review by a PSC is needed

/ocabot migration website_sale_suggest_create_account

**Pull request merged**
