### PR TITLE
[MIG] website_sale_product_reference_displayed: Migration to 17.0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by DorianMAG — APPROVED** [review]
Tested in runboat
Everything work, to find the button go in website -> editing and select product block

LGTM thx

Screenshot 2024-06-18 at 11-51-48 Shop My Website

Screenshot 2024-06-18 at 11-55-36 Shop My Website

**Comment by ghost** [comment]
Hello @OCA/website-maintainers 
Can you remove the stale tag ?

**Comment by DorianMAG** [comment]
@flotho @gaelTorrecillas
Can you make a review plz?

**Review by gaelTorrecillas — APPROVED** [review]

**Comment by tarteo** [comment]
@jdidderen-nsi I don't have access to do that. It's better to ask @OCA/e-commerce-maintainers that

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration website_sale_product_reference_displayed
/ocabot merge nobump

**Pull request merged**
