### PR TITLE
[16.0][MIG] website_sale_attribute_filter_form_submit: migration to 16.0

### PR DESCRIPTION
**Pull request by miguel-S73**
Standard migration from this PR https://github.com/OCA/e-commerce/pull/717

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Thanks @miguel-S73 :+1:

**Comment by miguel-S73** [comment]
@chienandalu  Recently I added compatibility with filters in mobile view.

**Review by chienandalu — APPROVED** [review]
Thanks @miguel-S73

**Review by ioans73 — APPROVED** [review]
LGTM 👍🏻

**Comment by miguel-S73** [comment]
@pedrobaeza Can you merge this PR? 
Recenty, https://github.com/OCA/e-commerce/pull/717 PR origin has been merged.

**Pull request merged**
