### PR TITLE
8.0 backport website_portal_sale from V9 to V8

### PR DESCRIPTION
**Pull request by oscarolar**

### CODE REVIEW

**Comment by oscarolar** [comment]
This Backport is the same than https://github.com/OCA/website/pull/69
just moved to the correct project.

**Comment by pedrobaeza** [comment]
You should respect commit history.

**Comment by nhomar** [comment]
@pedrobaeza which commit history?

**Comment by nhomar** [comment]
@pedrobaeza forget my last comment , it was an stupid question.

**Comment by oscarolar** [comment]
Sure, I will

**Pull request closed without merging**
