### PR TITLE
[16.0][MIG] website_sale_product_brand: Migration to 16.0

### PR DESCRIPTION
**Pull request by miguel-S73**
Standard migration.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
pre-commit problem being tackled in https://github.com/OCA/oca-addons-repo-template/pull/183

/ocabot migration website_sale_product_brand

**Review by antoniocanovas — APPROVED** [review]
Functional review Ok !!

**Comment by ConesaJM** [comment]
Everything works good!

**Comment by ConesaJM** [comment]
Everything looks good

**Review by ConesaJM — COMMENTED** [review]
Everything looks good!

**Review by ConesaJM — APPROVED** [review]

**Comment by ioans73** [comment]
@pedrobaeza could you merge this?

**Pull request merged**
