### PR TITLE
[13.0][ADD]Website Account Fiscal Position Partner Type

### PR DESCRIPTION
**Pull request by ValentinVinagre**
Issue: https://github.com/OCA/l10n-spain/issues/1718
Depend: https://github.com/OCA/account-fiscal-rule/pull/206
To Do:

- [X] Usage.rst
- [X] Description.rst

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
Functional review 👍

**Comment by HaraldPanten** [comment]
@pedrobaeza @Yajo do you mind adding a review to this one, please? 🙏

**Comment by pedrobaeza** [comment]
What about the TODOs?

**Comment by HaraldPanten** [comment]
README will be finished today.

I don't think we've time enough to prepare some tests today, but your review would be appreciated to check the main structure of the module. If we've to apply important changes (other than tests) we'll finish them today.

THX

**Comment by HaraldPanten** [comment]
As it is still a Beta version, maybe I could add this to the Roadmap instead.

You know it's been a project in which we couldn't have valuable info until the last days before applying the legislation.

WDYT? @pedrobaeza

**Comment by pedrobaeza** [comment]
OK about the TODOs, but we are not able to review, as we don't have OSS in our customers, and the controller thing requires testing, as reading code is usually not enough.

**Comment by HaraldPanten** [comment]
> OK about the TODOs, but we are not able to review, as we don't have OSS in our customers, and the controller thing requires testing, as reading code is usually not enough.

OK!

@sergiocorato @dreispt @OSevangelist Could you add some technical reviews, please?

**Comment by HaraldPanten** [comment]
@pedrobaeza This Beta version is ready to merge. Could you do that for us?

THX

**Comment by pedrobaeza** [comment]
Travis is red.

**Comment by HaraldPanten** [comment]
oops, sorry, we've to check pre-commit first

**Comment by HaraldPanten** [comment]
Full green @pedrobaeza

**Comment by pedrobaeza** [comment]
Well, there's only one review, and not technical, but I merge in beta status:

/ocabot merge nobump

**Comment by HaraldPanten** [comment]
> Well, there's only one review, and not technical, but I merge in beta status:
> 
> /ocabot merge nobump

THX Pedro!

**Comment by ValentinVinagre** [comment]
> Well, there's only one review, and not technical, but I merge in beta status:
> 
> /ocabot merge nobump

:O it's a christmas present.

**Pull request merged**
