### PR TITLE
[MIG] website_sale_product_attribute_value_filter_existing: Migration to v.12.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT20149

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by chienandalu — COMMENTED** [review]
Is this module needed anymore? From Odoo v12 runbot:
attribute-filter

**Comment by sergio-teruel** [comment]
@chienandalu OHHHHH the module is not available..... 
Selección_500

**Comment by sergio-teruel** [comment]
@chienandalu If you create a new duration attribute value like as "5 Year" and any product has this value, this one is hidden in website attribute's filter

**Review by chienandalu — APPROVED** [review]
Great, understood :+1:

**Pull request merged**
