### PR TITLE
[14.0][ADD] website_sale_attribute_filter_form_submit

### PR DESCRIPTION
**Pull request by miguel-S73**
This module hides all the submit elements of the attribute filter form,block submitting the form in the 'onchange' attributes values and it add a submit button at the end of the filters.

attribute_filter_submit

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Testing in runbot, I see a problem selecting the color attributes. I think it could be achieved with bare bootstrap though. I similar case I resolved that way: https://github.com/OCA/rma/blob/12.0/rma_sale/views/sale_portal_template.xml#L45-L53

**Comment by chienandalu** [comment]
Amending my comment, I tried some options:

- Removing the opacity of the checkbox input: easiest but ugly
- Adding an overlay via css that changes depending on the checked selector (something like [this](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_custom_checkbox)): tricky and unreliable
- Styling the label (which is the one holding the color swatch style) via js: reliable and medium

So maybe we should go for the last one

**Comment by miguel-S73** [comment]
Ok, I will try it

**Comment by chienandalu** [comment]
> Ok, I will try it

@miguels73 take a look at #535 at last it was quite simple

**Comment by chienandalu** [comment]
@miguels73 #535 is already merged can you adapt the changes from https://github.com/OCA/e-commerce/pull/535/commits/4b3f896295e0b4b1621142f644f03eedc9af5374 to your PR?

**Comment by miguel-S73** [comment]
Hi @chienandalu , I have tested your changes and it works fine but I can't cherry-pick your changes because commit brings more changes. Do you know any way to do it? Or do I commit and make you a contributor?

**Comment by miguel-S73** [comment]
@chienandalu , I have already applied your changes.

**Review by chienandalu — APPROVED** [review]
Thanks @miguels73 :)

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
