### PR TITLE
Adding contributors in readme.rst

### PR DESCRIPTION
**Pull request by bvanjeelharia**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check the RST syntax

**Comment by pedrobaeza** [comment]
And please don't add more than one commit.

**Review by chienandalu — CHANGES_REQUESTED** [review]
This has the same issue that the former one. You have to add your changes to readme/CONTRIBUTORS.rst

**Comment by bvanjeelharia** [comment]
Hello David,

I need to add it in both files, right?

Thanks and Regards,
[image: Logo] <https://www.brainvire.com/> [image: Logo]
Anjeel Haria
Software Engineer
M: +91 00000 00000
P: +91-22-61163300 / *EXTN:* 100
E: ***@***.***
W: www.brainvire.com
[image: Facebook icon] <https://www.facebook.com/Brainvire> [image:
LinkedIn icon] <https://www.linkedin.com/company/brainvire-infotech-inc/>
[image:
Twitter icon] <https://twitter.com/Brainvire> [image: Blog]
<https://www.brainvire.com/blog/?utm_source=email-signature>
[image: Company of the Year]
<https://www.brainvire.com/brainvire-recognized-as-company-of-the-year/>
[image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#review-491817> [image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#reviews> [image:
Digital Best Commerce Development Company]
<https://www.brainvire.com/recognized-as-best-ecommerce-development-company/>
[image:
Good Firms Top Web Developers]
<https://www.goodfirms.co/companies/view/1512/brainvire-infotech-inc>

Disclaimer: The information transmitted by this email is intended only for
the person or entity to which it is addressed. This email may contain
proprietary, business-confidential and/or privileged material. Please
consider the environment before printing.

**Comment by chienandalu** [comment]
Not really. The main one is generated automatically

**Comment by bvanjeelharia** [comment]
Ok fine thanks
Thanks and Regards,
[image: Logo] <https://www.brainvire.com/> [image: Logo]
Anjeel Haria
Software Engineer
M: +91 00000 00000
P: +91-22-61163300 / *EXTN:* 100
E: ***@***.***
W: www.brainvire.com
[image: Facebook icon] <https://www.facebook.com/Brainvire> [image:
LinkedIn icon] <https://www.linkedin.com/company/brainvire-infotech-inc/>
[image:
Twitter icon] <https://twitter.com/Brainvire> [image: Blog]
<https://www.brainvire.com/blog/?utm_source=email-signature>
[image: Company of the Year]
<https://www.brainvire.com/brainvire-recognized-as-company-of-the-year/>
[image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#review-491817> [image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#reviews> [image:
Digital Best Commerce Development Company]
<https://www.brainvire.com/recognized-as-best-ecommerce-development-company/>
[image:
Good Firms Top Web Developers]
<https://www.goodfirms.co/companies/view/1512/brainvire-infotech-inc>

Disclaimer: The information transmitted by this email is intended only for
the person or entity to which it is addressed. This email may contain
proprietary, business-confidential and/or privileged material. Please
consider the environment before printing.

**Review by chienandalu — APPROVED** [review]
Now it's fine :smile: :+1:

**Review by pedrobaeza — APPROVED** [review]
Next time, please try to do this on one step in the initial PR or just prevent this addition.

/ocabot merge patch

**Pull request merged**
