### PR TITLE
[ADD] website_sale_survey: require surveys before selling products

### PR DESCRIPTION
**Pull request by yajo**
This module extends the functionality of eCommerce and surveys to support
requiring online customers to fill a survey when buying certain products.

TT28205

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@Yajo you read my mind 🥇

**Review by sergio-teruel — APPROVED** [review]
Functional review...
Thanks

**Review by chienandalu — APPROVED** [review]
:+1:

**Review by joao-p-marques — APPROVED** [review]
Code and functional review :+1: 

Travis is red

**Comment by pedrobaeza** [comment]
@Yajo if this is finished, we can merge it.

**Comment by yajo** [comment]
Almost. There was a little bug when public user was buying and answering the survey. If you still think it's worth it I can do it 🤷🏼‍♂️

**Comment by pedrobaeza** [comment]
Well, if @ValentinVinagre wants to continue the work, here it is. If not everything is done, then we shouldn't expense more time on it, as an alternative approach has been already required.

**Pull request closed without merging**
