### PR TITLE
[13.0][FIX]website_sale_product_sort: call super with ppg value.

### PR DESCRIPTION
**Pull request by jesusVMayor**
#574 

CC: @pedrobaeza

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Thanks

**Comment by pedrobaeza** [comment]
Fast-tracking it following 12.0 PR:

/ocabot merge patch

**Review by HaraldPanten — APPROVED** [review]
Same as previous version PR

**Comment by pedrobaeza** [comment]
@jesusVMayor please pass pre-commit for this.

**Comment by jesusVMayor** [comment]
:+1:

**Pull request merged**
