### PR TITLE
[16.0][MIG] website_sale_hide_price: Migration to 16.0

### PR DESCRIPTION
**Pull request by JrAdhoc**

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Tested. Looks good :+1: Thanks!

**Review by pedrobaeza — COMMENTED** [review]
Something that I have discovered that is not probably of the migration itself is that if you have attributes with extra price, they are still shown:

Selección_002

so please cover also this option, or at least put it on the roadmap section.

**Comment by JrAdhoc** [comment]
@pedrobaeza thanks for your feedback. I added a t-if on that element with the same condition as the other elements present in that view. Alredy ammended the PR aswell

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Comment by tricorebv** [comment]
Hey, I noticed the price is still showing up to Public User when searching for a product in the search bar.

Screenshot 2023-02-03 at 10 39 07

Am I missing something to hide it?

**Comment by chienandalu** [comment]
@tricorebv sure. It looks like an issue with the search box. Can you open the issue or propose a patch?

**Pull request merged**
