### PR TITLE
[15.0][MIG]website_sale_category_breadcrumb: Migration to 15.0

### PR DESCRIPTION
**Pull request by bizzappdev**

### CODE REVIEW

**Comment by bizzappdev** [comment]
ready for review

**Review by chienandalu — CHANGES_REQUESTED** [review]
Works as expected. The only problem is that you mixed up the migration commit with the pre-commit one. Check the migration guide to do it correctly: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch

**Comment by bizzappdev** [comment]
> Works as expected. The only problem is that you mixed up the migration commit with the pre-commit one. Check the migration guide to do it correctly: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch

Do you mean version change?
pre-commit is always falling if we do not have the proper version.

**Comment by chienandalu** [comment]
That's why on the guidelines that changes are commited whit the flag `--no-verify`:
```bash
git commit -m "[IMP] $MODULE: black, isort, prettier"  --no-verify
```

**Pull request closed without merging**
