### PR TITLE
WIP [12.0] portin website_sale_suggest_create_account

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't see the migration commit changing at least manifest version. You can try also the readme by fragments system.

**Comment by eLBati** [comment]
I am doing it :running_man:  I just wanted to let people know I am working on it

**Comment by pedrobaeza** [comment]
Perfect. Maybe it's better to simply put a comment on migration issue. Let me know if you need assistance with the readme part.

**Comment by eLBati** [comment]
It should be ready, but travis is overloaded I think

**Comment by pedrobaeza** [comment]
Yeah, we have increased the number of concurrent builds, but not enough for the high jam.

**Review by yajo — APPROVED** [review]
It looks very nice:

captura de pantalla de 2018-10-02 10-33-59

**Comment by yajo** [comment]
Fast-tracking, code sprint stamina mode :rocket:

**Pull request merged**
