### PR TITLE
[12.0][FIX]website_sale_product_sort: call super with ppg value.

### PR DESCRIPTION
**Pull request by jesusVMayor**
Prevents the lost of ppg parameter.
cc: @chienandalu

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Is this applicable to upper versions?

/ocabot merge patch

**Comment by jesusVMayor** [comment]
> Is this applicable to upper versions?

Yes, exists the same error in 13.0

**Comment by pedrobaeza** [comment]
Please perform the PR for solving it there.

**Pull request merged**
