### PR TITLE
[13.0][IMP] website_sale_attribute_filter_category: Collapsible attributes

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT26949

This PR is a forward port of the commits:

-  https://github.com/OCA/e-commerce/commit/ee6e2c1e126ba3b34979d50d508f22c290f21e9d#diff-0445f43da774c31b7852c27a8fe4ff6a9515fb3349f6664d5a2bc024bfc47bb5
- https://github.com/OCA/e-commerce/commit/854dcf001925545dfceef1edd574d1008f043aae#diff-0445f43da774c31b7852c27a8fe4ff6a9515fb3349f6664d5a2bc024bfc47bb5
- https://github.com/OCA/e-commerce/commit/628801b337a4927f7440f4fad1639886d130a183#diff-0445f43da774c31b7852c27a8fe4ff6a9515fb3349f6664d5a2bc024bfc47bb5

Please @Tardo @sergio-teruel review this

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Why not to cherry pick them?

**Comment by CarlosRoca13** [comment]
I had to adapt the commits to the 13 version... But done @chienandalu

**Comment by pedrobaeza** [comment]
@chienandalu can you check?

**Review by chienandalu — APPROVED** [review]
Tested :+1:

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
