### PR TITLE
[13.0][FIX]website_account_fiscal_position_partner_type: force calculation fiscal position

### PR DESCRIPTION
**Pull request by ValentinVinagre**
Case:
1.- Go e-commer with public user.
2.- Buy something.
3.- Complete the purchase without registering.
4.- The fical position doesn't recalculate.

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@HaraldPanten could you review?

**Comment by HaraldPanten** [comment]
@ValentinVinagre Could you check travis?

**Comment by ValentinVinagre** [comment]
> @ValentinVinagre Could you check travis?

done!

**Comment by HaraldPanten** [comment]
@pedrobaeza could you shed some light here?

Travis is failing because of "_Connection Error while trying to connect to Chrome debugger after 7 tries_"

On the other hand, OCB build is working fine. 🤔

**Review by HaraldPanten — APPROVED** [review]
Functional review.

**Comment by pedrobaeza** [comment]
Retried to see

**Comment by HaraldPanten** [comment]
> Retried to see

Travis doesn't mess with you 😂

THX

**Review by oihane — APPROVED** [review]
LGTM

**Comment by HaraldPanten** [comment]
@pedrobaeza could you merge this one, please?

THX!

**Comment by pedrobaeza** [comment]
Why are you calling an onchange that can do a lot of things instead of computing the part you want? It also seems weird that regular flow doesn't do all the stuff.

**Pull request closed without merging**
