### PR TITLE
[8.0][website_sale_product_legal] Tiny cosmetic fix

### PR DESCRIPTION
**Pull request by yajo**
Just making code look prettier, this must have passed unnoticed before... Sorry for that.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Squash the commits in one

**Comment by yajo** [comment]
Sorry, edited directly on GitHub, done.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1:

**Pull request merged**
