### PR TITLE
[14.0][MIG] website_sale_stock_available

### PR DESCRIPTION
**Pull request by ivantodorovich**
Standard migration

Depends on https://github.com/OCA/stock-logistics-warehouse/pull/1037

### CODE REVIEW

**Review by bosd — APPROVED** [review]
LGTM :+1:  Functional review!

**Review by chienandalu — CHANGES_REQUESTED** [review]
Thanks @ivantodorovich Can you check the fail on travis?

**Comment by ivantodorovich** [comment]
I'm not sure where the error is coming from, it's not related to the code.
I rebased on 14.0, hopefully the build will be green now

**Comment by bosd** [comment]
Glad to see green travis. But why the red crosses on codecov? Does that still hold this one from being merged?

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
