### PR TITLE
[12.0][FIX] website_sale_secondary_unit: Remove sudo access to avoid to display unpublished secondary units.

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT31018

ping @chienandalu @CarlosRoca13

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I don't think we should change this, as we are leaking information to public. Instead, you should filter specifically on the published attribute on the controller/Qweb.

**Comment by chienandalu** [comment]
I don't see any leak. The record rule is there to avoid showing more than it's published: https://github.com/OCA/e-commerce/blob/b81325fb59c09f21e3deace004dea4c9c81000b2/website_sale_secondary_unit/security/website_sale_secondary_unit.xml#L7-L8

**Review by chienandalu — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
OK then

**Comment by sergio-teruel** [comment]
Thanks!!

**Comment by chienandalu** [comment]
This should be forward ported, isn't it?

**Pull request merged**
