### PR TITLE
[ADD] website_sale_vat_required

### PR DESCRIPTION
**Pull request by eLBati**
This module extends checkout e-commerce form in order to force user to fill 'VAT number' field

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This should be on website project, doesn't it?

**Comment by eLBati** [comment]
@pedrobaeza Isn't website project for CMS modules mainly?

**Comment by pedrobaeza** [comment]
No, website it's for modules that modify front-end things, like this one. You have also selected _website_sale_ prefix for this reason. Please move it, and take the ocassion to select a more specific icon than the cart icon (putting an overlayed VAT word for example).

**Comment by eLBati** [comment]
Ok @pedrobaeza , done with https://github.com/OCA/website/pull/24

**Pull request closed without merging**
