### PR TITLE
[12.0][FIX] website_sale_secondary_unit: Fixed price computation

### PR DESCRIPTION
**Pull request by CarlosRoca13**
Before this changes, the change in the value of the secondary unit input field
didn't launch the execution of the onchanges of the real input field.

Adding this changes, we achieve to capture the event of the new input field
to launch the onchanges of the real input field.

cc @Tecnativa TT29708

please @sergio-teruel @joao-p-marques review this

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by sergio-teruel — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@chienandalu has commented internally a problem with this patch.

**Comment by pedrobaeza** [comment]
Is this finished?

**Comment by CarlosRoca13** [comment]
@pedrobaeza yes, it is

**Review by joao-p-marques — APPROVED** [review]

**Pull request merged**
