### PR TITLE
[13.0] [FIX] website_sale_product_detail_attribute_image : update CSS url from less to scss

### PR DESCRIPTION
**Pull request by zeroheure**
Odoo 13 doesn't use less anymore. Change it to scss.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check Travis

**Comment by pedrobaeza** [comment]
I think you have forgotten to rename the underlying file (and maybe convert it).

**Comment by zeroheure** [comment]
Done. Sorry, I allways forget something.

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
As basic change, fast-tracking it:

/ocabot merge minor

**Pull request merged**
