### PR TITLE
[MIG] website_sale_stock_provisioning_date: Migration to 14.0

### PR DESCRIPTION
**Pull request by miguel-S73**
Standard migration to 14.0

Added extra commit to favor cherry-pick. This commit fix this:

The provisioning date was always showing in the same format without
respecting the date format defined in the language settings.

It is added in function `_get_combination_info` instead of in function
`_get_next_provisioning_date` so that the date is still formatted even
if function `_get_next_provisioning_date` is inherited.

### CODE REVIEW

**Comment by miguel-S73** [comment]
@pedrobaeza , ¿How do you see this PR?

**Review by fuentes73 — APPROVED** [review]

**Comment by fuentes73** [comment]
@ernestotejeda as you are the author could you please review?

**Review by ioans73 — APPROVED** [review]
LGTM 👍🏻

**Comment by pedrobaeza** [comment]
Please rebase and run pre-commit to add `setup` folder files.

**Comment by miguel-S73** [comment]
@pedrobaeza rebase and run pre-commit to add `setup` folder files applied.

**Pull request merged**
