### PR TITLE
[12.0][ADD] website_sale_product_style_badge

### PR DESCRIPTION
**Pull request by Tardo**
badges

cc @tecnativa TT23634

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
:+1: Very poweful :)

Check travis anyway

**Comment by Tardo** [comment]
Travis green

**Review by pedrobaeza — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
