### PR TITLE
[14.0][MIG] website_sale_hide_empty_category

### PR DESCRIPTION
**Pull request by ilyasProgrammer**

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
functional ok!

@OCA/e-commerce-maintainers good for you?

**Comment by Aldeigja** [comment]
LGTM!

**Review by Aldeigja — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@OCA/website-maintainers migration ok? :)

**Review by chienandalu — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@OCA/e-commerce-maintainers could this be merged? thanks!

**Comment by francesco-ooops** [comment]
@pedrobaeza could you? thanks!

**Comment by pedrobaeza** [comment]
For next times, please put the name of the module correctly (with _ instead of spaces), as a lot of people search for that name.

/ocabot migration website_sale_hide_empty_category
/ocabot merge nobump

**Comment by francesco-ooops** [comment]
> For next times, please put the name of the module correctly (with _ instead of spaces), as a lot of people search for that name.

@ilyasProgrammer

**Pull request merged**
