### PR TITLE
[12.0][ADD] website_sale_attribute_filter_category_collapsable

### PR DESCRIPTION
**Pull request by Tardo**
Extends website_sale_attribute_filter_category with collapsable sections for the attributes. The website_sale_attribute_filter_category module only collapse the category.

attribute_filter_collapse

cc @tecnativa TT25329

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why that huge indentation?

**Comment by Tardo** [comment]
@pedrobaeza it happens because of this rule: https://github.com/odoo/odoo/blob/ab3605081801bc2772c7bf2987096a9b6034c0c8/addons/website_sale/static/src/scss/website_sale.scss#L9

**Comment by pedrobaeza** [comment]
But is it something general without this module? If so, let's keep it that way and fix it on themes.

**Review by chienandalu — CHANGES_REQUESTED** [review]
Thanks @Tardo 

- Check travis for sytax and lint errors
- Isn't it possible to get the same visually compact result as in collapsable categories?:
image

**Comment by Tardo** [comment]
@chienandalu this module doesn't add any CSS rule or "ul" elements... maybe can be done in base 'website_sale_attribute_filter_category' but i thinkg that this must be handle by a custom theme.

**Comment by chienandalu** [comment]
> @chienandalu this module doesn't add any CSS rule or "ul" elements... maybe can be done in base 'website_sale_attribute_filter_category' but i thinkg that this must be handle by a custom theme.

Well, I meant using the same bootstrap classes as in the standard collapsable categories

**Comment by Tardo** [comment]
If we want change the visual behaviour, we need change 'website_sale_attribute_filter_category' module first. This implementation of collapsable elements is better because uses unicode character inyected in css... but yeah, breaks the visual style with Odoo implementation.

website_sale_attribute_filter_category and website_sale_attribute_filter_category_collapsable both modules adds collapsable zones.

@sergio-teruel ping!

**Comment by sergio-teruel** [comment]
> If we want change the visual behaviour, we need change 'website_sale_attribute_filter_category' module first

Ok... do it if necessary.
Why haven't you expanded the website_sale_attribute_filter_category module instead of create a new one?
But for me Ok for the module...

**Review by sergio-teruel — APPROVED** [review]
Only if you can review css

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Let's go for the inclusion of this in the other module as a customize_show option.

**Pull request closed without merging**
