### PR TITLE
[FIX] Validate pikcing was broken during the port to the new version

### PR DESCRIPTION
**Pull request by sebastienbeau**
Hi during the port to the new version the workflow method was not pass correctly to the picking.
Indeed even if a method was set on the sale order no method was set on picking.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You don't need to propagate the data to the procurement group. You can get it this way:

```
move.procurement_id.sale_line_id.order_id.workflow_process_id
```

**Comment by gurneyalex** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Please take into account my remark to avoid a new field.

**Comment by sebastienbeau** [comment]
This have been fixed in sale_workflow

**Pull request closed without merging**
