### PR TITLE
[10.0][IMP] product_template_multi_link: Several improvements

### PR DESCRIPTION
**Pull request by rousseldenis**
* Supersedes #406 
* Backport of #316 : Makes link bi-directional 
* Add indexes
* Adapt wizard from #406 to bi-directional approach

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Cedric-Pigeon @lmignon @acsonefho This is a merge PR of several improvements in order to have no conflicts.

**Comment by lmignon** [comment]
@rousseldenis We have 2 entries for le links into the menu... one for product.template and one for product.product. Unfortunately, there is nothing to distinguish which one is for which model.
image

**Comment by rousseldenis** [comment]
> @rousseldenis We have 2 entries for le links into the menu... one for product.template and one for product.product. Unfortunately, there is nothing to distinguish which one is for which model.
> image

Ok, I'll check

**Review by lmignon — APPROVED** [review]
A little comment otherwise LGTM (Code review + Functional tests)

**Review by Cedric-Pigeon — APPROVED** [review]

**Pull request merged**
