### PR TITLE
[16.0][MIG] website_sale_suggest_create_account: Migration to version 16.0

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
This PR supersedes https://github.com/OCA/e-commerce/pull/705

cc @Tecnativa TT44387

@chienandalu @CarlosRoca13 please review :)

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]
LGTM :+1:

**Review by chienandalu — COMMENTED** [review]
Can you push again to get a runbot?

**Comment by pedrobaeza** [comment]
Runboat is not working from yesterday. GH is returning 422 error to the runboat service, as @sbidoul commented yesterday, but now there's no bad status on hooks according status page.

**Comment by chienandalu** [comment]
Oh, thanks. I'll test locally then

**Review by chienandalu — COMMENTED** [review]
I'd simplify it. To me, it makes more sense this behavior:

Sign in/up checkout:

- optional -> Sign in/up and checkout 
- disabled -> Sign in and checkout button
- mandatory -> Sign in/up and checkout (the same one that in the first place)

Indeed you just need to change the button text

**Comment by pilarvargas-tecnativa** [comment]
> I'd simplify it. To me, it makes more sense this behavior:
> 
> Sign in/up checkout:
> 
> * optional -> Sign in/up and checkout
> * disabled -> Sign in and checkout button
> * mandatory -> Sign in/up and checkout (the same one that in the first place)
> 
> Indeed you just need to change the button text

I have made the change in the button names but in the "mandatory" option it is not allowed to checkout without being registered/logged in, by default the login button appears and I have also added the registration button.

In short, the three options are:

- Optional: allows checkout as guest/register/log in (v15 free sign up). Button: sign in/up and checkout
- Disable: allow checkout as guest/log in (v15 on invitation). Button: sign in and checkout
- Mandatory: do not allow guest checkout/allow sign in and login (the functionality of website_sale_require_login). Button: sign up (sign in is already by default)

**Comment by chienandalu** [comment]
> * Mandatory: do not allow guest checkout/allow sign in and login (the functionality of website_sale_require_login). Button: sign up (sign in is already by default)

Then just change the original text to Sign in/up. The place for the user to decide whether to create a new account or to log in with an existing one is /web/login

**Comment by pilarvargas-tecnativa** [comment]
> /web/login

The changes are already made to both the button name/link and the template, so it would appear in the "Mandatory" option:
image

**Review by chienandalu — APPROVED** [review]
Thanks! :)

**Review by CarlosRoca13 — APPROVED** [review]
By making these changes we are adding the functionality of the https://github.com/OCA/e-commerce/tree/15.0/website_sale_require_login module to this one, right?

If so, please add the necessary migration scripts.

**Comment by pilarvargas-tecnativa** [comment]
> By making these changes we are adding the functionality of the https://github.com/OCA/e-commerce/tree/15.0/website_sale_require_login module to this one, right?
> 
> If so, please add the necessary migration scripts.

website_sale_require_login has been merged into website_sale, here is the migration script:
https://github.com/OCA/OpenUpgrade/pull/4113

**Comment by CarlosRoca13** [comment]
Thx :smile:

**Comment by pilarvargas-tecnativa** [comment]
@pedrobaeza Can this be merged?

**Comment by pedrobaeza** [comment]
You should squash administrative commits and the translations commits from the same author (not mixing languages).

**Comment by pilarvargas-tecnativa** [comment]
> You should squash administrative commits and the translations commits from the same author (not mixing languages).

done, thanks :)

**Comment by pedrobaeza** [comment]
@pilarvargas-tecnativa can you please rebase and push to see if the error is reproducible now on the PR?

**Comment by pedrobaeza** [comment]
So the error persists... It seems Odoo has changed recently something, and it's not still propagated to OCB. Can you please check deeper?

**Comment by pilarvargas-tecnativa** [comment]
> So the error persists... It seems Odoo has changed recently something, and it's not still propagated to OCB. Can you please check deeper?

But now the error is in the tests, the same one that comes and goes as it pleases. I investigate and replicate locally to see what I can find out.

**Comment by pedrobaeza** [comment]
It only fails persistently in Odoo one (not OCB). You locally have OCB. Please check with Odoo latest source code to see.

**Pull request merged**
