### PR TITLE
[12.0] [MIG] website_sale_affiliate module

### PR DESCRIPTION
**Pull request by chafique-delli**

### CODE REVIEW

**Comment by chafique-delli** [comment]
Ping @DarkoNikolovski , @rafaelbn , @pedrobaeza .

**Comment by HaraldPanten** [comment]
Could you check runbot?

**Comment by chafique-delli** [comment]
@HaraldPanten , it's fixed, all checks are green.

**Comment by desdelinux** [comment]
Ping @DarkoNikolovski , @rafaelbn , @pedrobaeza .

**Review by desdelinux — APPROVED** [review]
Functional Revision is Ok

**Review by claudiagn — APPROVED** [review]
LGTM! functional review ok

**Pull request closed without merging**
