### PR TITLE
[15.0][MIG] website_sale_invoice_address: Migration to version 15.0

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
@Tecnativa TT36995
@chienandalu please review
ping @ernestotejeda  @victoralmau

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Thanks! @pilarvargas-tecnativa

**Review by victoralmau — APPROVED** [review]
Good job.

Code and functionality review.

**Comment by francesco-ooops** [comment]
@pilarvargas-tecnativa does it look to you like this module is currently not working as expected?

Functional test on runbot failed for me

**Comment by francesco-ooops** [comment]
@chienandalu too FYI :)

**Comment by pedrobaeza** [comment]
Please open an issue mentioning the steps to reproduce the problem, and a video would be also good.

**Comment by francesco-ooops** [comment]
@pedrobaeza sure, I wrote here because I saw there was a recent commit referencing this PR.

**Comment by francesco-ooops** [comment]
@pedrobaeza @chienandalu actually the module is working as described, but it can improved functionally. Here is the issue: #739 

we will port it to v.14 and try to improve it :)

**Pull request merged**
