### PR TITLE
[15.0] [MIG] website_sale_tax_toggle: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36610

please @willytal @Tardo review this

### CODE REVIEW

**Review by willytal — APPROVED** [review]

**Comment by CarlosRoca13** [comment]
ping @sergio-teruel

**Review by chienandalu — COMMENTED** [review]
The tax toggle widget only shows up correctly with an admin user context:

image

Other users (even internals) will show up a simple checkbox:

image

image

**Comment by CarlosRoca13** [comment]
Ughh, thanks, I will review it

**Comment by CarlosRoca13** [comment]
Solved and rebase done :wink:

**Review by chienandalu — APPROVED** [review]
Great!

**Pull request merged**
