### PR TITLE
[13.0][NEW]website_sale_category_breadcrumb

### PR DESCRIPTION
**Pull request by Rad0van**
Displays full (recursive) breadcrumb for selected product category. Also allows for displaying breadcrumbs for any additional categories of the product.

### CODE REVIEW

**Comment by miguel-S73** [comment]
functional review OK

**Review by miguel-S73 — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
:+1:

**Comment by Rad0van** [comment]
@miguels73 and @chienandalu please have a look here: https://github.com/OCA/website/pull/745 This has long been in a process. Thanx.

**Pull request merged**
