### PR TITLE
[14.0][IMP] website_sale_product_item_cart_custom_qty

### PR DESCRIPTION
**Pull request by dessanhemrayev**
Add a setting in /shop page > customize: Always display qty buttons 
Qty and add to cart buttons are always visible (not only on rollover) 
To improve the visualization, move the buttons below the image so that they do not overlap it, now it occupies about 20% of the image height.

### CODE REVIEW

**Comment by CarlosRoca13** [comment]
Please review tests

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

@CarlosRoca13 can we merge?

**Review by CarlosRoca13 — CHANGES_REQUESTED** [review]
Something does not work as expected.

image

When scrolling down, all the add-to-cart buttons have been stuck loading

**Comment by francesco-ooops** [comment]
> Something does not work as expected.
> 
> image
> 
> When scrolling down, all the add-to-cart buttons have been stuck loading

@CarlosRoca13 this issue is present in current runboat as well, so it's not due to this PR. 

Would it be possible to merge? :)

**Review by francesco-ooops — CHANGES_REQUESTED** [review]
actually it shouldn't be merged, 

@dessanhemrayev when I click on "add to cart" nothing happens

**Review by CarlosRoca13 — CHANGES_REQUESTED** [review]
I think the option that has been introduced is very restrictive and should not eliminate the existing design. Previously, when the Add to cart option was active and the module installed, hovering over the products makes the buttons appear to indicate the quantity. I don’t want this to be lost.

The new feature should be just that, a new feature, but not break the previous behavior.

**Comment by dessanhemrayev** [comment]
@CarlosRoca13  I returned the previous button behavior and combined them with the new one. Please take a look.)

**Review by CarlosRoca13 — APPROVED** [review]
:+1:  Thanks

**Review by francesco-ooops — APPROVED** [review]
Functional is ok!

@CarlosRoca13 can we merge?

**Comment by francesco-ooops** [comment]
@CarlosRoca13 a question: qty button is visibly unaligned with "add to cart" and "wishlist", resulting in a very "sloppy" feeling for the ecommerce:

image

anything that could be done to fix it?

**Comment by CarlosRoca13** [comment]
> @CarlosRoca13 a question: qty button is visibly unaligned with "add to cart" and "wishlist", resulting in a very "sloppy" feeling for the ecommerce:
> 
> image
> 
> anything that could be done to fix it?

Hmmm... Has the add to cart any margin top?

**Comment by francesco-ooops** [comment]
@CarlosRoca13 I'm not technical and cannot say, so I thought to ask you as maybe you know better how it works :)

I see this is slightly affecting v15 (while in v16 it's fine)

image

**Comment by CarlosRoca13** [comment]
I will take a look when i have a chance

**Pull request merged**
