### PR TITLE
[15.0] [MIG] website_sale_hide_empty_category: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36600

please @Tardo @sergio-teruel review this

### CODE REVIEW

**Comment by JrAdhoc** [comment]
@CarlosRoca13 @Tardo @sergio-teruel 
Is this PR ready for merging?

**Comment by pedrobaeza** [comment]
Please review it: https://odoo-community.org/resources/review

**Comment by JrAdhoc** [comment]
@pedrobaeza 
runboat build is not available. I get this {"detail":"Not Found"}

**Comment by pedrobaeza** [comment]
@JrAdhoc I have rebased to trigger a new build and now it should work.

**Comment by JrAdhoc** [comment]
@pedrobaeza Thanks! 
@CarlosRoca13 Thanks for the migration!

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
You can't merge. You have to do a review using GitHub flow, and approve it saying if it's a functional review or code one, and a bit of explanation if you want ("I have done this and this and test that it works...").

**Review by JrAdhoc — APPROVED** [review]
Functional review +1. 
Tested frontend behaviour when leaving an ecommerce category empty. Works fine

**Review by pedrobaeza — APPROVED** [review]
Code review

**Pull request merged**
