### PR TITLE
[14.0][MIG] website_sale_require_legal: Migration to V14

### PR DESCRIPTION
**Pull request by navarrorico**
Tested in 14.0 and no changes needed.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please review #464 instead, and for other times, you should reserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0.

**Comment by navarrorico** [comment]
Ok. I will review #464 but website_sale_require_legal has nothing to do with website_sale_require_login as far as I know.

**Comment by pedrobaeza** [comment]
Sorry, my bad. I have mixed both. Then please preserve commit history and the PR will be OK.

**Comment by willytal** [comment]
@navarrorico Hi, I've seen you have already opened a PR. Are you still working on it?

**Comment by navarrorico** [comment]
@willytal No, sorry. You can continue with the migration, the module works in v14, the only thing that I failed is in the migration steps.

**Pull request closed without merging**
