### PR TITLE
[REL] website_sale_exception: Migration to 13.0

### PR DESCRIPTION
**Pull request by zaoral**

### CODE REVIEW

**Comment by ivantodorovich** [comment]
travis is complaining because of the missing oca_dependency, can you add it?

**Comment by zaoral** [comment]
Hi @ivantodorovich 

Thank you for your review.
I have added the sale-workflow depenendency,
However, since the sale_exception 13.0 PR has not been merged yet I think that the travis will raise the same error :(

**Comment by ivantodorovich** [comment]
Yeap.. 

Depends on https://github.com/OCA/sale-workflow/pull/1051, which also depends on https://github.com/OCA/server-tools/pull/1760

**Comment by ivantodorovich** [comment]
I'm guessing this PR only needs a rebase to be green

**Pull request closed without merging**
