### PR TITLE
[12.0][ADD] website_sale_attribute_filter_order

### PR DESCRIPTION
**Pull request by Tardo**
order

cc @tecnativa TT23634

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
It doesn't work for me in runbot:
attr-sort

**Comment by Tardo** [comment]
@chienandalu you need enable the option in "customize" menu ;)

**Comment by Tardo** [comment]
Hope that now works fine with `website_sale_product_attribute_value_filter_existing`

**Review by chienandalu — APPROVED** [review]
:+1: Cool, thanks :)

**Review by pedrobaeza — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]
LGTM 👍

**Pull request merged**
