### PR TITLE
[MIG] website_sale_hide_price: Migration to 13.0

### PR DESCRIPTION
**Pull request by maitaoriana**

### CODE REVIEW

**Comment by maitaoriana** [comment]
Hi @pedrobaeza, the migration is ready, please could you review it? Thanks

**Comment by pedrobaeza** [comment]
I have added the PR to the migration issue, but I'm not a qualified reviewer.

**Comment by tonygalmiche** [comment]
I failed to do this on runbot :
`If you wanted to have the prices hidden by default when no user is logged in you should go to Public User's partner and set Show prices on website off.`
I did this, but the prices are still displayed

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Review by chienandalu — APPROVED** [review]
Looks like the compare views still show the price
image

**Comment by pedrobaeza** [comment]
@chienandalu then it's not an approval?

**Review by chienandalu — CHANGES_REQUESTED** [review]
Oh, sorry

**Comment by maitaoriana** [comment]
@chienandalu Thanks by you review

I think that to hide the price on the comparator is not the responsibility of this module because it would need to depend on website_sale_comparison. Besides on v 12 this module doesn't hide the prices on the comparator. [Video](https://drive.google.com/file/d/1STlgTo0N3fY1xMuymn09r7q_2rqy7M1V/view)

To add this new feature would be good to create a new module that depends on this module and website_sale_comparison module.

**Review by chienandalu — APPROVED** [review]
Ok, great :+1:

**Pull request merged**
