### PR TITLE
[MIG] website_sale_product_detail_attribute_image: Migration to 14.0

### PR DESCRIPTION
**Pull request by miguel-S73**
Standard migration to 14.0

### CODE REVIEW

**Review by emagdalenaC2i — COMMENTED** [review]
Please, rename  website_sale_product_detail_attribute_image/static/src/img/EN374:2003.png 
See #381 and #382

**Comment by miguel-S73** [comment]
> Please, rename website_sale_product_detail_attribute_image/static/src/img/EN374:2003.png
> See #381 and #382

fixed

**Comment by bosd** [comment]
Functional test, LGTM

**Review by bosd — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
