### PR TITLE
[IMP] website_sale_product_detail_attribute_image: Better response view.

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Not sure about this one... Please put some screenshots with large texts.

**Review by rafaelbn — APPROVED** [review]
Super great improvement :+1: thanks!
Teste in runbot!

**Review by martintorresvm — APPROVED** [review]
Code LGTM

**Comment by rafaelbn** [comment]
@sergio-teruel i miss two mistakes in readme

**Pull request closed without merging**
