### PR TITLE
[FIX][12.0] website_sale_product_available_display: Take into account negative units to display danger style message

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT24520
@chienandalu @Tardo Can you review, please!!

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]
Small FIX

**Comment by sergio-teruel** [comment]
@chienandalu @HaraldPanten I have added an extra commit to compute virtual_available units with a context.
The website_sale_product_available module allow compute quantities based in other fields depending of a context key...
I have taken advantage of this PR, Sorry!!!

**Comment by sergio-teruel** [comment]
ping @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
Yeah, this kind of coupling is not the best, but putting the following parameters:

- Performance
- Side effects
- Code clarity

I think it's the best balance and as both modules are OCA and the comment is explicitly enough

**Comment by pedrobaeza** [comment]
As @chienandalu is on holidays, and @HaraldPanten already approved the main topic of the PR and the addition is harmless, I proceed to merge

/ocabot merge minor

Anyway, if you have any cons, I can abort it.

**Pull request merged**
