### PR TITLE
[13.0][MIG] website_sale_vat_required: Migration to 13.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
cc @Tecnativa TT25964

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
Functional review 👍 

Just check Travis

**Review by victoralmau — CHANGES_REQUESTED** [review]
Functional review work fine but travis error appear related tour test.

**Comment by HaraldPanten** [comment]
Hi @ernestotejeda could you have a look at travis related comments?

THX!

**Comment by pedrobaeza** [comment]
Please rebase

**Comment by ernestotejeda** [comment]
@pedrobaeza @HaraldPanten ready to review

**Comment by HaraldPanten** [comment]
Functionally working fine. Tested on runbot

**Pull request merged**
