### PR TITLE
[8.0][IMP][website_sale_product_legal] Use Bootstrap dialog instead of jQuery UI

### PR DESCRIPTION
**Pull request by yajo**
This provides better theme consistency and less dependencies.

CC @rafaelbn @dgzurita.

### CODE REVIEW

**Comment by yajo** [comment]
This should be ready to review.

**Comment by JavierIniesta** [comment]
Tested in runbot. :+1:

**Comment by rafaelbn** [comment]
Tested in runbot logen as admin y without login.
This is just and improvement for the popup changing js by bootstrap and work fine so I think I can merge
:+1:

**Comment by dgzurita** [comment]
Tested in runbot. :+1:

**Comment by JMODaERP** [comment]
Tested in runbot :+1:

**Comment by yajo** [comment]
Enough :+1: IMHO.

**Comment by janetrp** [comment]
works as expected. Tested in runbot :+1: 
2015-11-18 16_00_07-ipad mini _ localhost
2015-11-18 16_00_22-ipad mini _ localhost

.

**Pull request merged**
