### PR TITLE
[MIG] website_sale_checkout_skip_payment: Migration to 11.0

### PR DESCRIPTION
**Pull request by chienandalu**
This module allows to logged users to checkout with no payment step.

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You should preserve commit history the same as being in the same repository. You need to add 2 remotes (one for e-commerce and another for website), and adapt the command for importing from the other remote.

Check also Travis and runbot status.

**Comment by chienandalu** [comment]
Sorry, I commited the wrong local branch :confounded:

**Comment by chienandalu** [comment]
Anyway, the v9 repo was still e-commerce

**Review by cristinamartinrod — APPROVED** [review]
Works fine! 👍🏼

**Comment by rafaelbn** [comment]
Hello! @chienandalu @cristinamartinrod we should look for an existing migrations before doing a new one :smile: this module was migrated in https://github.com/OCA/e-commerce/pull/228 long time ago!

**Comment by rafaelbn** [comment]
Hi @chienandalu , i'm closing this one as duplicated. Please make a PR to improve https://github.com/OCA/e-commerce/tree/11.0/website_sale_checkout_skip_payment with:

- Readme
- If you are not logged and you add to cart and product with a different pricelist and after that you login then you get and SO with different pricelist than you have assigned in you company. Should it be fixed?
- Coverage?

**Comment by chienandalu** [comment]
> If you are not logged and you add to cart and product with a different pricelist and after that you login then you get and SO with different pricelist than you have assigned in you company. Should it be fixed?

@rafaelbn I don't understand well what you ask here and what does it has to do with this module :thinking:

**Pull request closed without merging**
