### PR TITLE
[MIG] website_sale_attribute_filter_price: Migration to 14.0

### PR DESCRIPTION
**Pull request by ioans73**
Standard migration to 14.0

### CODE REVIEW

**Comment by dalonsod** [comment]
@ioans73 could you check #479 ? The PR is not ported to v13 yet, but it can be added here.

**Comment by ioans73** [comment]
> @ioans73 could you check #479 ? The PR is not ported to v13 yet, but it can be added here.

I have cherry-picked the commit

**Comment by dalonsod** [comment]
Tested on runbot, shop Customize menu doesn't show Price Filter option. Could you check @ioans73 ? Maybe I'm doing something wrong...

**Comment by ioans73** [comment]
> Tested on runbot, shop Customize menu doesn't show Price Filter option. Could you check @ioans73 ? Maybe I'm doing something wrong...

First you must activate the option 'Product attribute's filters' and then the option 'Price Filter' will be displayed

**Comment by dalonsod** [comment]
Thanks @ioans73 , LGTM
Related to my "issue" enabling the feature, maybe REAMDE documentation should be improved with the previous option that must be enabled before, but not blocking.

**Review by dalonsod — APPROVED** [review]

**Review by fuentes73 — APPROVED** [review]

**Comment by miguel-S73** [comment]
I have added a class to use the primary colors of odoo. In this way, if the user changes the styles of website, these will also be modified.

**Review by bosd — APPROVED** [review]

**Comment by bosd** [comment]
How can we get this to merge? Is there an PSC to  trigger ocabot? 
Maybe @Yajo

**Comment by bosd** [comment]
ping @OCA/e-commerce-maintainers

**Pull request merged**
