### PR TITLE
[15.0] [MIG] website_sale_suggest_create_account: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36609

superseded from https://github.com/OCA/e-commerce/pull/619 as the author is giving no response.
I respect his commit and correct the failing tests recovering the original ones

please @Tardo @pedrobaeza review this

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Tested on runboat + code review

Please squash your migration amends into one instead of putting them split in 2

**Comment by CarlosRoca13** [comment]
Done @pedrobaeza

**Comment by JrAdhoc** [comment]
@pedrobaeza Is this ready for merging?

**Comment by pedrobaeza** [comment]
@JrAdhoc please do a functional review and approve it for proceeding with the merge:

https://odoo-community.org/resources/review

**Comment by JrAdhoc** [comment]
Functional review +1

@pedrobaeza

**Comment by pedrobaeza** [comment]
Thanks for the review. You can use GitHub tools for the approval next time.

Merging:

/ocabot merge nobump

**Pull request merged**
