### PR TITLE
[14.0][ADD] website_sale_delivery_group

### PR DESCRIPTION
**Pull request by ivantodorovich**
This module provides a way to group shipping methods on the website checkout page.
Particularly useful when the company offers lots of shipping methods 

Example:
website_sale_delivery_group

### CODE REVIEW

**Review by mamcode — APPROVED** [review]
LGTM :+1:

**Comment by ioans73** [comment]
Functional review

**Review by ioans73 — APPROVED** [review]

**Comment by ivantodorovich** [comment]
Hello @OCA/e-commerce-maintainers can we merge this?

**Review by chienandalu — APPROVED** [review]
Cool one :+1:

**Comment by bosd** [comment]
ping @OCA/e-commerce-maintainers

**Pull request merged**
