### PR TITLE
Add module website_sale_categories_megamenu.

### PR DESCRIPTION
**Pull request by yajo**
Relaunch https://github.com/OCA/website/pull/81.

Product categories megamenu.

cc @rafaelbn @dgzurita @moylop260.

### CODE REVIEW

**Comment by dgzurita** [comment]
Tested in runbot :+1:

**Comment by antespi** [comment]
:+1: same as original, tested in runbot and code review

**Comment by rafaelbn** [comment]
said in https://github.com/OCA/website/pull/81 :+1:

**Comment by pedrobaeza** [comment]
You haven't allowed me to change the module name to singular when merging, that was my plan. I'll do it now with direct commit.

**Comment by pedrobaeza** [comment]
@Yajo, there's 2 points that you can improve:
- Include an screenshot of the menu in the README.
- Use a minimized screenshot as module icon.

**Comment by oscarolar** [comment]
I think you should wait for all time zones in the world at least to review the code, this was really fast and couldn't review it before merge, created some issues tho.

**Comment by pedrobaeza** [comment]
Well, that one was a bit fast, but it comes a PR in another branch. Anyway, you can make a PR for improving/fixing whatever you find.

**Pull request merged**
