### PR TITLE
[MIG] website_sale_resource_booking: Migration to 13.0

### PR DESCRIPTION
**Pull request by yajo**
Depends on:

- [x] https://github.com/OCA/sale-workflow/pull/1763
- [x] https://github.com/OCA/calendar/pull/60

@Tecnativa TT31328

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]
Code review ok.
It's ready to review.
Ping @chienandalu @pedrobaeza

**Review by chienandalu — APPROVED** [review]
Tested :+1: Thanks :)

**Pull request merged**
