### PR TITLE
[FIX] website_sale_product_available_display: Take into account negative units to display danger style message

### PR DESCRIPTION
**Pull request by sergio-teruel**
Minor fix
cc @Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]
small fix. LGTM

**Comment by pedrobaeza** [comment]
Let's fast-track it: /ocabot merge patch

**Comment by pedrobaeza** [comment]
@sergio-teruel you need to check Travis

**Pull request merged**
