### PR TITLE
[15.0][MIG+IMP] website_account_fiscal_position_partner_type

### PR DESCRIPTION
**Pull request by manuelregidor**
MIG: Standard migration
IMP: Show fiscal_position_type in user detals view in portal, show fiscal_position_type in registration screen, avoid changing fiscal_position_type under certain circumstances.

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by HaraldPanten — APPROVED** [review]

**Review by ValentinVinagre — CHANGES_REQUESTED** [review]
When registering, the company's default option does not work. Could you check it?
Selección_042

**Comment by manuelregidor** [comment]
> When registering, the company's default option does not work. Could you check it? Selección_042

@ValentinVinagre Done

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by HaraldPanten** [comment]
@pedrobaeza @chienandalu how come these tests fail for the OCB but the others in the FIX (20 minutes ago) have been successful? 😂

We'll have a look and check it.

**Comment by chienandalu** [comment]
> @pedrobaeza @chienandalu how come these tests fail for the OCB but the others in the FIX (20 minutes ago) have been successful? 😂
> 
> We'll have a look and check it.

Maybe a random fail. I'd try again

**Comment by HaraldPanten** [comment]
@pedrobaeza Finally it's done.

Could you merge, please?

**Comment by pedrobaeza** [comment]
/ocabot migration website_account_fiscal_position_partner_type
/ocabot merge nobump

**Comment by HaraldPanten** [comment]
Thanks Pedro. It was a resistant one.

**Pull request merged**
