### PR TITLE
[14.0] [MIG] website sale product description

### PR DESCRIPTION
**Pull request by bosd**
Standard migration

### CODE REVIEW

**Comment by bosd** [comment]
This is the port of https://github.com/OCA/e-commerce/pull/524

**Comment by bosd** [comment]
@chienandalu Could you please review?

**Comment by bosd** [comment]
@dalonsod Could you please review?

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Review by chienandalu — APPROVED** [review]
Code review. Not tested :+1:

**Review by dalonsod — APPROVED** [review]
Tested on runbot 👍

**Comment by bosd** [comment]
ping @OCA/e-commerce-maintainers

Edit: Tag is not working.
Hello @OCA/ecommerce-maintainers can you merge this?

**Comment by bosd** [comment]
@pedrobaeza Can you please merge this one as well?

**Pull request merged**
