### PR TITLE
[MIG] product_template_multi_link_date_span: Migration to 14.0

### PR DESCRIPTION
**Pull request by dzungtran89**
Dependencies:
- product_template_multi_link: https://github.com/OCA/e-commerce/pull/489

### CODE REVIEW

**Comment by simahawk** [comment]
https://github.com/OCA/e-commerce/pull/489 merged please rebase and drop the dependency

**Comment by simahawk** [comment]
please fwd port https://github.com/OCA/e-commerce/pull/498

**Comment by hailangvn** [comment]
Thanks @simahawk for your comments. The PR has been updated accordingly. Let us know if anything else is needed.

**Comment by simahawk** [comment]
@hailangvn not a blocker but any good reason for squashing all new commits? It makes harder to understand what has been ported on what not and hides what happened on the module (which is why atomic commits are nice) :wink:

**Comment by hailangvn** [comment]
Thanks @simahawk, the PR has been updated. The only reason is to reduce number of commits and it has low priority. :)

**Comment by simahawk** [comment]
> Thanks @simahawk, the PR has been updated. 

thanks!

> The only reason is to reduce number of commits and it has low priority. :)

there's no reason to reduce number of commits if they are meaningful :wink:

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
@chafique-delli can you review this?

**Review by sebalix — APPROVED** [review]

**Review by mmequignon — APPROVED** [review]

**Pull request merged**
