### PR TITLE
[12.0] ADD website_sale_product_model_viewer

### PR DESCRIPTION
**Pull request by eLBati**
Depends on https://github.com/OCA/product-attribute/pull/660

### CODE REVIEW

**Review by mamcode — APPROVED** [review]
LGTM :+1:

**Comment by eLBati** [comment]
Green and ready

**Comment by andreampiovesana** [comment]
just add /static/description/icon.png

**Comment by eLBati** [comment]
@andreampiovesana what icon would you add?

**Comment by andreampiovesana** [comment]
OCA

Andrea Piovesana Linux Mint 19.3www.pnlug.it



Il giorno ven 28 ago 2020 alle ore 08:10 Lorenzo Battistini <
notifications@github.com> ha scritto:

**Comment by pedrobaeza** [comment]
It will be automatically added on merge by bot.

**Review by andreampiovesana — APPROVED** [review]
go

**Review by HaraldPanten — APPROVED** [review]
Functional review 👍

**Pull request merged**
