### PR TITLE
[15.0][MIG] product_variant_multi_link

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Standard migration

- [x] Depends on https://github.com/OCA/e-commerce/pull/684

CC @ForgeFlow

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@OCA/e-commerce-maintainers please remove "stale" tag

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
https://github.com/orgs/OCA/teams/e-commerce-maintainers please remove "stale" label and reopen the PR

**Comment by pedrobaeza** [comment]
Please rebase and check the CI problem.

**Comment by MiquelRForgeFlow** [comment]
> Please rebase and check the CI problem.

It's not related to this PR:

Selection_1727
Selection_1728

**Pull request closed without merging**
