### PR TITLE
[15.0][FIX] website_sale_product_item_cart_custom_qty

### PR DESCRIPTION
**Pull request by Aldeigja**
Adaptive design is fixed as [requested](https://github.com/OCA/e-commerce/pull/799#pullrequestreview-1426025252)

### CODE REVIEW

**Review by geomer198 — APPROVED** [review]
LGTM!

**Comment by pedrobaeza** [comment]
@pilarvargas-tecnativa is this taken into account in v16?

**Comment by pilarvargas-tecnativa** [comment]
> @pilarvargas-tecnativa is this taken into account in v16?

Not taken into account in v16, the fix must also be applied to v16.

**Comment by pedrobaeza** [comment]
Please proceed

**Pull request merged**
