### PR TITLE
[16.0][IMP] e-commerce : test performance improvement

### PR DESCRIPTION
**Pull request by josep-tecnativa**
CC @Tecnativa TT45458

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Comment by pedrobaeza** [comment]
Oh, please solve conflicts, @josep-tecnativa

**Comment by josep-tecnativa** [comment]
> Oh, please solve conflicts, @josep-tecnativa

Done

**Pull request merged**
