### PR TITLE
[16.0][MIG] website_sale_stock_provisioning_date: Migration to version 16.0

### PR DESCRIPTION
**Pull request by ernesto-garcia-tecnativa**
@tecnativa TT44233

### CODE REVIEW

**Comment by ernesto-garcia-tecnativa** [comment]
@pedrobaeza @chienandalu please review

**Review by chienandalu — APPROVED** [review]
Thanks @ernesto-garcia-tecnativa :)

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
