### PR TITLE
[16.0][MIG] website_sale_product_reference_displayed: Migration to 16.0

### PR DESCRIPTION
**Pull request by bvanjeelharia**

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Thanks @bvanjeelharia Tested an code review. Anyway, squash your migration commits into a single one

**Comment by bvanjeelharia** [comment]
Hello David,

I have squashed my migration commits

Thanks and Regards,
Anjeel Haria

**Comment by chienandalu** [comment]
Ouch, you merged migration changes with the pre-commit stuff ones :/

**Comment by bvanjeelharia** [comment]
Hello David,

Sorry for the trouble, I have pushed the changes again along with the
pre-commit stuff

Thanks and Regards,
[image: Logo] <https://www.brainvire.com/> [image: Logo]
Anjeel Haria
Software Engineer
M: +91 00000 00000
P: +91-22-61163300 / *EXTN:* 100
E: ***@***.***
W: www.brainvire.com
[image: Facebook icon] <https://www.facebook.com/Brainvire> [image:
LinkedIn icon] <https://www.linkedin.com/company/brainvire-infotech-inc/>
[image:
Twitter icon] <https://twitter.com/Brainvire> [image: Blog]
<https://www.brainvire.com/blog/?utm_source=email-signature>
[image: Company of the Year]
<https://www.brainvire.com/brainvire-recognized-as-company-of-the-year/>
[image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#review-491817> [image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#reviews> [image:
Digital Best Commerce Development Company]
<https://www.brainvire.com/recognized-as-best-ecommerce-development-company/>
[image:
Good Firms Top Web Developers]
<https://www.goodfirms.co/companies/view/1512/brainvire-infotech-inc>

Disclaimer: The information transmitted by this email is intended only for
the person or entity to which it is addressed. This email may contain
proprietary, business-confidential and/or privileged material. Please
consider the environment before printing.

**Review by chienandalu — APPROVED** [review]
Thanks @bvanjeelharia ! Oh, and you can put yourself as contributor in the README

**Review by flotho — APPROVED** [review]
code review + tested on roboat,LGTM

**Pull request merged**
