### PR TITLE
[14.0][MIG] website_sale_product_attribute_value_filter_existing: migration to 14.0

### PR DESCRIPTION
**Pull request by miguel-S73**
Standard migration

### CODE REVIEW

**Comment by miguel-S73** [comment]
Please, can anyone review this PRs?

@CarlosRoca13 , @sergio-teruel , @pedrobaeza

**Comment by CarlosRoca13** [comment]
Yes sure, please rebase to use runboat

**Comment by miguel-S73** [comment]
> Yes sure, please rebase to use runboat

Rebase done and all checks green.

**Comment by miguel-S73** [comment]
@CarlosRoca13  ¿Could you please review?

**Comment by CarlosRoca13** [comment]
LGTM :+1: Tested on runboat

**Review by CarlosRoca13 — APPROVED** [review]

**Review by fuentes73 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
/ocabot migration website_sale_product_attribute_value_filter_existing
/ocabot merge nobump

**Pull request merged**
