### PR TITLE
Adding contributor in README.rst

### PR DESCRIPTION
**Pull request by bvanjeelharia**

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Comment by bvanjeelharia** [comment]
Hello David,

The OCA bot removed my name from the contributors list, why is that? can
you please let me know?


Thanks and Regards,
[image: Logo] <https://www.brainvire.com/> [image: Logo]
Anjeel Haria
Software Engineer
M: +91 00000 00000
P: +91-22-61163300 / *EXTN:* 100
E: ***@***.***
W: www.brainvire.com
[image: Facebook icon] <https://www.facebook.com/Brainvire> [image:
LinkedIn icon] <https://www.linkedin.com/company/brainvire-infotech-inc/>
[image:
Twitter icon] <https://twitter.com/Brainvire> [image: Blog]
<https://www.brainvire.com/blog/?utm_source=email-signature>
[image: Company of the Year]
<https://www.brainvire.com/brainvire-recognized-as-company-of-the-year/>
[image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#review-491817> [image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#reviews> [image:
Digital Best Commerce Development Company]
<https://www.brainvire.com/recognized-as-best-ecommerce-development-company/>
[image:
Good Firms Top Web Developers]
<https://www.goodfirms.co/companies/view/1512/brainvire-infotech-inc>

Disclaimer: The information transmitted by this email is intended only for
the person or entity to which it is addressed. This email may contain
proprietary, business-confidential and/or privileged material. Please
consider the environment before printing.

**Comment by pedrobaeza** [comment]
Because you didn't do the modification on `readme` subfolder. I didn't pay attention of that when you did the PR.

**Comment by bvanjeelharia** [comment]
Thanks for the clarification. I will raise a PR again
Thanks and Regards,
[image: Logo] <https://www.brainvire.com/> [image: Logo]
Anjeel Haria
Software Engineer
M: +91 00000 00000
P: +91-22-61163300 / *EXTN:* 100
E: ***@***.***
W: www.brainvire.com
[image: Facebook icon] <https://www.facebook.com/Brainvire> [image:
LinkedIn icon] <https://www.linkedin.com/company/brainvire-infotech-inc/>
[image:
Twitter icon] <https://twitter.com/Brainvire> [image: Blog]
<https://www.brainvire.com/blog/?utm_source=email-signature>
[image: Company of the Year]
<https://www.brainvire.com/brainvire-recognized-as-company-of-the-year/>
[image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#review-491817> [image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#reviews> [image:
Digital Best Commerce Development Company]
<https://www.brainvire.com/recognized-as-best-ecommerce-development-company/>
[image:
Good Firms Top Web Developers]
<https://www.goodfirms.co/companies/view/1512/brainvire-infotech-inc>

Disclaimer: The information transmitted by this email is intended only for
the person or entity to which it is addressed. This email may contain
proprietary, business-confidential and/or privileged material. Please
consider the environment before printing.

**Pull request merged**
