### PR TITLE
[FIX][11.0][website_sale_hide_price] Disable Add to cart option to prevent show prices in cart

### PR DESCRIPTION
**Pull request by JuanjoA**
PR to solve issue #242

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@AbrahamTrey what do you think about this?

**Comment by JuanjoA** [comment]
@AbrahamTrey , have you been able to test?

**Comment by rafaelbn** [comment]
@antoniocanovas @pedroguirao-ic please review here :smile:

**Review by rafaelbn — APPROVED** [review]
Tested functionally in runbot :+1:

**Comment by rafaelbn** [comment]
@chienandalu @antoniocanovas @pedroguirao-ic please review here! Thanks!!! :smile:

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
