### PR TITLE
[ADD] website_no_price_on_main

### PR DESCRIPTION
**Pull request by gfcapalbo**
Identify a website (or multiple websites)  as "main", all prices will not be shown on these website(s).

### CODE REVIEW

**Comment by pedrobaeza** [comment]
And why not letting this be selected on `website` model?

**Comment by gfcapalbo** [comment]
> And why not letting this be selected on `website` model?

website.config.settings seems naturally the place. obviously, is_main is defined on website.
in v9 website.config.settings is more accessible for the website manager than website.
seemed like a natural fit.

**Comment by pedrobaeza** [comment]
But why it should be only on main? If I want to hide the prices in 2 websites, this module has all the base, but limit artificially the possibility.

**Comment by gfcapalbo** [comment]
The module would work with multiple websites set as "is_main" . this module derived from a user request who needed 1 main website with no prices. The variable name "is_main" is not expressive of  that usecase, but it will work if you set 2-3 ..n websites as "is_main". the is_main flag is set per-website. so it will will work.

**Comment by pedrobaeza** [comment]
But then call it "Hide prices" instead of "Is main"...

Any way, there's a module https://github.com/OCA/e-commerce/tree/11.0/website_sale_hide_price that performs the same. You should expand that one for being selectable at website level.

**Comment by gfcapalbo** [comment]
@pedrobaeza  agreed with extension , closing MR. will do.

**Pull request closed without merging**
