### PR TITLE
8.0 sale quick payment

### PR DESCRIPTION
**Pull request by gurneyalex**
port sale_quick_payment to v8

### CODE REVIEW

**Comment by gurneyalex** [comment]
updated version of #46

**Comment by guewen** [comment]
Since there is a button to display the payments (https://github.com/gurneyalex/e-commerce/blob/8.0-sale_quick_payment/sale_payment_method/sale_view.xml#L19-L23) I think we could remove the `payment_ids` field from the sales orders' view.

**Comment by bguillot** [comment]
Thanks this module is needed ! :+1:

**Comment by guewen** [comment]
:+1:

**Comment by rafaelbn** [comment]
Hi @gurneyalex:
- In order yo have same place for everything, don't you think is better yo have a tab in sales order for payments as in invoices?

After trying to test this module I have doubts sorry... 
- this is a module for e-commerce and this module install sale_payment_method
- In e-commerce usually payment are done throug Paypal, Ogone, Stripe, Credit Card, ...
- This module sale_quick_payment I guess helps to sale online and receive the payment in the sale order

Why is not related with how the customer paid (payment.acquirer)?

When customer buy online you would like to have their purchases "quick paid" when the payment is done through the payment.acquirer. How you make this with this module?

Thanks

**Comment by guewen** [comment]
> this is a module for e-commerce and this module install sale_payment_method
>     In e-commerce usually payment are done throug Paypal, Ogone, Stripe, Credit Card, ...
>     This module sale_quick_payment I guess helps to sale online and receive the payment in the sale order

Hi @rafaelbn,

This set of modules (`sale_payment_method`, `sale_automatic_workflow`, ...) has never been thought in the context of the Odoo e-commerce modules (`website_sale`, ...).
These modules are used by the Magento, Prestashop (etc.) connectors when you don't necessary have the `website` modules installed.
Possibly an integration with the `payment.acquirer` would be possible, but I'm not sure about that. Anyway I don't think it could happen in 8.0 because the `sale_payment_method` module is already widely used.

**Comment by guewen** [comment]
@rafaelbn I think this project brings confusion because it mixes addons related to odoo's e-commerce and to e-commerce addons unrelated to it and both not always share the same path.

**Comment by pedrobaeza** [comment]
That's why we talked about moving this kind of modules to sale-workflow.

**Comment by guewen** [comment]
> That's why we talked about moving this kind of modules to sale-workflow.

totally!

**Comment by gurneyalex** [comment]
So this would be
- sale_quick_payment
- sale_sale_payment_method

Do we want to also move 
- sale_automatic_workflow
- sale_payment_method_automatic_workflow ?

**Comment by pedrobaeza** [comment]
Yeah, I think so, please see https://github.com/OCA/e-commerce/issues/47

**Comment by LeartS** [comment]
I agree. e-commerce is going to be a big part of Odoo with a lot of modules, we should try to keep it clean, at least for version 9.

**Comment by rafaelbn** [comment]
IMO we must move this four to sale-workflow. I agree with moving:
- sale_quick_payment
- sale_sale_payment_method
- sale_automatic_workflow
- sale_payment_method_automatic_workflow

Nothing has to be with e-commerce (website_sale - that why the name was [discussed here](https://odoo-community.org/groups/oca-contributors-15/oca-contributors-24218)).

In fact is more related with connector than Odoo's e-commerce.

About this theme, we are working in several e-commerce with Odoo, and we need to have different workflows depending if the sale is from backend or from e-commerce (obviously) and this means that we will work in (near future):
- website_sale_quick_payment
- website_sale_sale_payment_method
- website_sale_automatic_workflow
- website_sale_payment_method_automatic_workflow

**Comment by gurneyalex** [comment]
I'll change this over the week end.

**Comment by rafaelbn** [comment]
Hello, please when possible change this PR to https://github.com/OCA/sale-workflow as discussed.
Also discussed here: https://github.com/OCA/e-commerce/issues/47
Thanks

**Comment by gurneyalex** [comment]
Hi all,

I'm totally under the water, and need help on these PRs. I'd be very grateful if someone could pick them up and do the migration. @lepistone maybe you could lend me a hand here?

:heart_eyes_cat:

**Comment by lepistone** [comment]
ok, I'm picking this up.

**Comment by lepistone** [comment]
Superseded by #86 and OCA/sale-workflow#239.

**Pull request closed without merging**
