### PR TITLE
[16.0][FIX] website_sale_product_item_cart_custom_qty

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
Issue detected in v14, fixed in this PR https://github.com/OCA/e-commerce/pull/799.
In v16 the correction should be different.

cc @Tecnativa TT44385

ping @pedrobaeza @CarlosRoca13

### CODE REVIEW

**Review by chienandalu — CHANGES_REQUESTED** [review]
This isn't working as expected

image

**Comment by pilarvargas-tecnativa** [comment]
> This isn't working as expected

No... my local database was dirty in the test, I am correcting it.

**Comment by pilarvargas-tecnativa** [comment]
@chienandalu fixed

**Review by chienandalu — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
I'm seeing it a bit ugly on mobile view:

Selección_092

Even on full one it's a bit displaced to the left:

Selección_093

**Comment by pilarvargas-tecnativa** [comment]
> Even on full one it's a bit displaced to the left:

That is the standard odoo layout, you are including an extra element in that container with that style. It can be centred for this module only.

Mobile:
image

Full:
image

In fact when there are several "quick" icons and there is no space they are placed in tower

Mobile:
image

**Comment by pedrobaeza** [comment]
OK, and what about the price alignment? In your screenshot is correctly aligned. Currently it's not.

**Comment by pilarvargas-tecnativa** [comment]
> OK, and what about the price alignment? In your screenshot is correctly aligned. Currently it's not.

It is the behaviour of odoo, when having a bigger element it takes it out of the container, I am going to look for the solution for this module and that the price is put below for small views.

**Comment by pilarvargas-tecnativa** [comment]
@pedrobaeza modifying the container classes does this:

Tablet size approx.
image

Mobile:
image

**Review by pedrobaeza — APPROVED** [review]
That looks better

/ocabot merge minor

**Pull request merged**
