### PR TITLE
[12.0][IMP+FIX] website_sale_attribute_filter_category: collapsible

### PR DESCRIPTION
**Pull request by Tardo**
Adds new customize view to make all collapsible.

After some tries i think that the visual changes must be done in a new version. Changes will break themes, and perhaps other modules that have this dependency.

categ

cc @tecnativa TT25329

### CODE REVIEW

**Comment by Tardo** [comment]
@chienandalu @sergio-teruel ping!

**Comment by Tardo** [comment]
Ready to review

**Comment by pedrobaeza** [comment]
The initial GIF is the final state?

**Review by chienandalu — COMMENTED** [review]
> The initial GIF is the final state?

I just tested an indeed it is.

But why can't we get a similar aspect to the one in website categories?

**Review by sergio-teruel — COMMENTED** [review]
What about extra space fix??

**Comment by Tardo** [comment]
@sergio-teruel I think it's better to leave it for a new version... now requires changes that can break the visualization on themes (changes in nodes).

**Comment by Tardo** [comment]
New gif in first comment.

**Comment by pedrobaeza** [comment]
I still see a lot of indentation from initial collapsable title to the second one.

**Comment by Tardo** [comment]
@pedrobaeza yes... fix it requires modify nodes. This change will break themes, etc... I think it is better to leave it for a major version change.
What do you think?

**Comment by pedrobaeza** [comment]
I don't think so. Only play with the visibility, not with modifying nodes.

**Comment by Tardo** [comment]
Changes done, gif updated.

**Review by sergio-teruel — APPROVED** [review]

**Review by sergio-teruel — CHANGES_REQUESTED** [review]
Waiting fix travis...

**Comment by Tardo** [comment]
Travis Green

**Review by sergio-teruel — APPROVED** [review]

**Pull request merged**
