### PR TITLE
[14.0][FIX] website_sale_product_item_cart_custom_qty

### PR DESCRIPTION
**Pull request by geomer198**
Adaptive design is fixed.

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
[Video](https://recordit.co/KjImykSOW4)

On the left: this PR
On the right: current version

This improvement is for mobile version

image

**Comment by francesco-ooops** [comment]
@CarlosRoca13 what do you think?

**Review by CarlosRoca13 — APPROVED** [review]
Please check if this fix is needed in v15 too

**Comment by francesco-ooops** [comment]
> Please check if this fix is needed in v15 too

yes, we'll forward port it, can you proceed with merge?

**Comment by francesco-ooops** [comment]
@CarlosRoca13 can you try launching the merge command again?

**Pull request merged**
