### PR TITLE
[15.0][MIG] website_sale_affiliate

### PR DESCRIPTION
**Pull request by nikunjantala**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Comment by nikunjantala** [comment]
@pedrobaeza Can you help me for this existing PR, how can I add commit history? Because in the link that you sent, we must first need to do fortmat-patch to preserver history  and then push module. But in this PR, I already pushed code. or I need to create new PR ?

**Comment by pedrobaeza** [comment]
I already put them link with the instructions on my previous comment.

**Comment by pedrobaeza** [comment]
Keep these files in a safe place, and start the procedure from scratch, and finally overwrite the files with the final result you saved.

**Comment by nikunjantala** [comment]
Thank you Pedro

**Comment by dsolanki-initos** [comment]
@nikunjantala, Could you please adjust the commits as per the OCA's guidelines https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

**Comment by dsolanki-initos** [comment]
@pedrobaeza, Could you please review this PR?

**Comment by jans23** [comment]
@pedrobaeza As far as I see this PR complies with OCA's requirements and needs to be reviewed. Could you add a no-stale label, please?

**Comment by pedrobaeza** [comment]
@jans23 why don't you review the PR as well for getting this merged?

/ocabot migration website_sale_affiliate

**Comment by jans23** [comment]
yes, we try to find the time for more reviews in the coming weeks.

**Comment by zeroheure** [comment]
up

**Pull request closed without merging**
