### PR TITLE
[15.0][ADD] ecommerce_first_last_name

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Comment by dsolanki-initos** [comment]
Hello @jans23

I've already added and you can check this URL for the same and we can not add our website in OCA.

https://github.com/OCA/e-commerce/pull/634/commits/ca3662e46d46b0590a18f38272df90445f3060a8#diff-b1c42b789f6e978e94f0ca7a755db9217ec608b807486f2de58d4848aff22707R5

Regards,

Dhara Solanki

**Review by ikapasi-initos — APPROVED** [review]
Code review and functional tests. 
LGTM.

**Comment by dsolanki-initos** [comment]
@chienandalu can you please review this PR?

**Comment by dsolanki-initos** [comment]
@dalonsod Can you please review this PR?

**Comment by dsolanki-initos** [comment]
@HaraldPanten Can you please review this PR?

**Comment by dsolanki-initos** [comment]
@victoralmau Can you please review this PR?

**Comment by dsolanki-initos** [comment]
@oihane Could you please review this PR?

**Comment by dsolanki-initos** [comment]
Hello, @gurneyalex Could you please review this PR?

**Comment by jans23** [comment]
@rafaelbn from our perspective this module is ready to be merged. Any feedback? Would it be possible to add the no-stale label?

**Pull request closed without merging**
