### PR TITLE
[13.0][IMP] website_sale_stock_list_preview: Make tests more resilient

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT38689

ping @pedrobaeza @chienandalu

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why they are more resilient now?

**Comment by CarlosRoca13** [comment]
As the value of `available_threshold` was set by default if some module decrease this default, the test will fail, as the text rendered will be "In stock" instead of "5.000 Units available".

**Comment by pedrobaeza** [comment]
Please put that on the commit message then.

**Comment by CarlosRoca13** [comment]
Done @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
