### PR TITLE
[15.0][MIG] website_sale_secondary_unit: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36608

This module depends of:

- [x] https://github.com/OCA/sale-workflow/pull/2057

please @sergio-teruel @carlosdauden review this

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]

**Comment by sergio-teruel** [comment]
@CarlosRoca13 Review cart 

In V13
Selección_1373

In V15 is not correct
Selección_1374

**Comment by CarlosRoca13** [comment]
@sergio-teruel solved! Now in v15 we have to override the function `_submitForm` of `publicWidget.registry.WebsiteSale` to add the new fields added on products Form.

**Review by sergio-teruel — APPROVED** [review]
Please do a rebase, the PR https://github.com/OCA/sale-workflow/pull/2057 has been merged

**Pull request merged**
