### PR TITLE
[MIG] website_sale_stock_available: Migration to 16.0

### PR DESCRIPTION
**Pull request by bvanjeelharia**

### CODE REVIEW

**Review by chienandalu — CHANGES_REQUESTED** [review]
Take a look at #714 You need to adapt the module to Odoo core changes

**Comment by bvanjeelharia** [comment]
Hello @chienandalu , I have made the changes as per https://github.com/OCA/e-commerce/pull/714 , can you please review and approve the same

**Review by chienandalu — CHANGES_REQUESTED** [review]
I'd prefer you to use the now merged #714 as your main migration path as there are several formal improvements (updated readme, tests, etc). Hopefully there will be not much to do after that for the 16.0 migration

**Comment by bvanjeelharia** [comment]
@chienandalu , updated based on https://github.com/OCA/e-commerce/pull/714

**Review by chienandalu — APPROVED** [review]
Thanks! :slightly_smiling_face: :+1:

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration website_sale_stock_available
/ocabot merge nobump

**Pull request merged**
