### PR TITLE
[13.0] [ADD] website_sale_free_qty: New module to show the free qty for the products stocks.

### PR DESCRIPTION
**Pull request by nicomacr**
It's similar to website_sale_stock_available but using the odoo field free qty

### CODE REVIEW

**Review by jjscarafia — APPROVED** [review]
+1 tested on two customers, working properly

**Review by ioans73 — APPROVED** [review]
LGTM

**Comment by nicomacr** [comment]
@pedrobaeza could you review this PR and merge too?

**Pull request merged**
