### PR TITLE
[14.0][MIG] website_sale_b2x_alt_price: Migration to V14

### PR DESCRIPTION
**Pull request by ferran-S73**

### CODE REVIEW

**Comment by ferran-S73** [comment]
@OCA/website-maintainers any reviewer please?

**Review by CarlosRoca13 — APPROVED** [review]
Tested locally :+1:

**Comment by pedrobaeza** [comment]
@ferran-S73 please rebase and add setup files.

**Comment by ferran-S73** [comment]
> @ferran-S73 please rebase and add setup files.

@pedrobaeza done!

**Pull request merged**
