### PR TITLE
13.0 mig website sale product description

### PR DESCRIPTION
**Pull request by bosd**
Standard migration

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Looks good :+1:

**Review by okuryan — APPROVED** [review]

**Comment by okuryan** [comment]
Looks good! @pedrobaeza , can that be merged?

**Review by HaraldPanten — APPROVED** [review]

**Comment by bosd** [comment]
ping @OCA/e-commerce-maintainers
Hello @OCA\/e-commerce-maintainers can you please merge?

**Comment by bosd** [comment]
Tags aint working or I'm doing something wrong.
@pedrobaeza Can you please  merge this? :pleading_face:

**Comment by pedrobaeza** [comment]
You are abusing a bit... :wink: 

Merging blindly /ocabot merge nobump

**Comment by bosd** [comment]
@pedrobaeza Can you check the git-bot? Why is he taking so long to merge?

**Pull request merged**
