### PR TITLE
[10.0][IMP] migrated sale_require_login and dependency

### PR DESCRIPTION
**Pull request by ovnicraft**
Module from 9.0 is working ok, migrate to 10.0 without major changes

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's already a PR for this module. Please review #138 and maybe propose any change to that branch.

**Comment by ovnicraft** [comment]
@pedrobaeza the migration hasta latest commit Nov/2016 this is an issue :(. So if there is no response about this, OCA has any definition about close the abandon PR and continues with another proposed by community ?

**Comment by pedrobaeza** [comment]
Well, not exactly a procedure, but when someone doesn't respond in the PR, usual steps is to take over his/her work and create another PR. Continuing from the previous PR work or start from the scratch will depend on the complexity of the changes. Anyway, I see that this module depends on another one, so you should first migrate that one also, isn't it?

**Comment by ovnicraft** [comment]
@pedrobaeza I migrate both in this PR, so i review their changes and has the same changes (module works without major changes).

Open a new PR for dependency module?

**Comment by pedrobaeza** [comment]
Let's see if tomorrow there's an answer, and if not, please open first a PR for the dependency, and then we reuse this one for the website_sale_require_login.

**Comment by ovnicraft** [comment]
Ok 👍

**Comment by iledarn** [comment]
@pedrobaeza I would like you to take this instead of mine https://github.com/OCA/e-commerce/pull/138, since @ovnicraft has fixed what was not right and so much time has elapsed . Sorry I'm messing up

**Comment by yelizariev** [comment]
Seems like @Yajo's [review](https://github.com/OCA/e-commerce/pull/138#pullrequestreview-6975264) are not taken into account.  At least two obvious requests (move assets.xml to demo and runbot link) are not done

**Pull request closed without merging**
