### PR TITLE
[14.0][MIG] website_sale_require_login: Migration to 14.0

### PR DESCRIPTION
**Pull request by njeudy**
https://github.com/OCA/e-commerce/pull/464 seems to be closed, but need this module.

- I start from initOS branch
- rebase it to last 14.0 from oca
- add address controler in blocked addresses.

Don't now if it's a good way to propose again this PR ..

### CODE REVIEW

**Comment by njeudy** [comment]
Think pre-commit error is not related to me ? can anyone explain what can I do ?

**Comment by njeudy** [comment]
@Tardo @pedrobaeza can you help me to review this ?

**Comment by pedrobaeza** [comment]
For pre-commit, #864 should be finished. For the tests of this PR, check what is the problem.

**Comment by njeudy** [comment]
> For pre-commit, #864 should be finished. For the tests of this PR, check what is the problem.

Don't undestand ui js test .. when I try manually, it work, think I should find if the selector is correct ..

**Comment by pedrobaeza** [comment]
Look at 15.0 to see the changes done there if they are applicable here.

**Comment by Tisho99** [comment]
Hello @njeudy , are you willing to continue this PR?

I also have interest on migrating this module

**Review by Tisho99 — APPROVED** [review]
LGTM Functional and technical review

**Comment by njeudy** [comment]
I think this PR is ready now, just force push to restart all action. @pedrobaeza is it correct for you ?

**Comment by pedrobaeza** [comment]
Although your commit messages are not correct (and they should be both in one), let's merge it being something relatively old:

/ocabot merge nobump

**Pull request merged**
