### PR TITLE
[16.0][MIG] website_sale_product_assortment: Migration to version 16.0

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
cc @Tecnativa TT44381

@CarlosRoca13 @chienandalu please review

### CODE REVIEW

**Comment by pilarvargas-tecnativa** [comment]
ping @CarlosRoca13

**Review by CarlosRoca13 — APPROVED** [review]
Good Job :+1:

**Review by chienandalu — APPROVED** [review]
Thanks :)

**Comment by pilarvargas-tecnativa** [comment]
ping @pedrobaeza :)

**Comment by pilarvargas-tecnativa** [comment]
ping @pedrobaeza

**Comment by xAdrianCif** [comment]
Hello @CarlosRoca13  and @chienandalu , just out of ignorance and looking to improve in the future, what are the reasons for having validated and merged this PR and having ignored another one with the same code dated earlier even though it was cited? 

Thank you!

https://github.com/OCA/e-commerce/pull/854

**Comment by CarlosRoca13** [comment]
Hello @xAdrianCif and @suker, apologies for the inconvenience. We didn't notice the notifications in the email, and since we have the company's internal pull requests tracked, we have reviewed this one without checking if there was any previous one. Nevertheless, it's not easy to find the pull request by searching for the module name, as underscores haven't been used. If you enter the name correctly in the search, your pull request doesn't appear.

image

**Comment by xAdrianCif** [comment]
Understood, thank you @CarlosRoca13 .

**Pull request merged**
