### PR TITLE
[11.0][MIG] website_sale_require_login: basic mig  from v10 to v11

### PR DESCRIPTION
**Pull request by oscarolar**
Depends on
- [x] website_salesuggest_create_account: #225

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please one module per PR and take into account #222

**Comment by oscarolar** [comment]
will do two PRs, i can see #222 is approved, merge in order to rebase please

**Comment by oscarolar** [comment]
Depends on https://github.com/OCA/e-commerce/pull/225 to satisfy dependency tree

**Comment by yelizariev** [comment]
Usually OCA requires to keep original commit history. Check https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#technical-method-to-migrate-a-module-from-100-to-110-branch

**Comment by pedrobaeza** [comment]
I was about to say it :wink:

**Comment by yelizariev** [comment]
giphy 1

**Comment by oscarolar** [comment]
@Yajo  this is pretty much ready to review

**Review by yajo — APPROVED** [review]

**Comment by yajo** [comment]
Functional and code review 👍

**Review by njeudy — APPROVED** [review]
code review and test

**Pull request merged**
