### PR TITLE
[15.0][MIG] website_sale_product_attribute_filter_category: Migration to version 15.0

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
cc @Tecnativa TT37008

@chienandalu @sergio-teruel please review

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
The CI actions didn't come up. Can you try and push again?

**Comment by pilarvargas-tecnativa** [comment]
> The CI actions didn't come up. Can you try and push again?

Done!

**Review by chienandalu — APPROVED** [review]
Code and functional :+1:

**Review by sergio-teruel — APPROVED** [review]

**Comment by pedrobaeza** [comment]
It turns out that this was renamed to `website_sale_product_attribute_filter_category` in #456, but without renaming commit history.

I have aborted the merge. Let's respect the new name. Please do the git operation to rename the whole history + make the changes in translations and so on, and also mark it as such in our infrastructure.

**Comment by pedrobaeza** [comment]
Now it has been renamed with whole commit history:

/ocabot merge nobump

**Pull request merged**
