### PR TITLE
[18.0][MIG] website_sale_product_reference_displayed: Migration to 18.0

### PR DESCRIPTION
**Pull request by kobros-tech**
a simple migration as there were no test cases from the lower version

### CODE REVIEW

**Comment by kobros-tech** [comment]
@chienandalu 
@CarlosRoca13 
@claudiagn 
@ypapouin 

Please review the pull request 

Thanks

**Review by CarlosRoca13 — APPROVED** [review]
:+1: Tested locally, thanks :)

**Review by chienandalu — APPROVED** [review]
Thanks :+1:

**Pull request merged**
