### PR TITLE
[9.0][NEW] website_sale_stock_control_global: New module

### PR DESCRIPTION
**Pull request by sergio-teruel**
This module depends of https://github.com/OCA/e-commerce/pull/214
This module does not allow sale products in shop on line but take stock from all companies
cc @Tecnativa

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hi @sergio-teruel , https://github.com/OCA/e-commerce/pull/215 has been merged.

Here runbot says:

```
2017-10-27 17:51:56,430 143 [1;31m[1;49mERROR[0m openerp_template openerp.modules.graph: module website_sale_stock_control_global: Unmet dependencies: website_sale_stock_control, stock_available_global
```

Please add dependencies in order to test this one! Thanks!

**Comment by rafaelbn** [comment]
Please @sergio-teruel could you rebase in order to test! Thanks

**Comment by sergio-teruel** [comment]
@rafaelbn Rebase done!

**Review by chienandalu — COMMENTED** [review]
Maybe OCA dependency to `stock-logistics-warehouse` is missing?

**Comment by rafaelbn** [comment]
@pedrobaeza @sergio-teruel could you add the dependency please?

> Maybe OCA dependency to stock-logistics-warehouse is missing?

```
2018-04-19 07:33:24,678 23353 ERROR openerp_test openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
File "/home/travis/odoo-9.0/openerp/modules/registry.py", line 386, in new
openerp.modules.load_modules(registry._db, force_demo, status, update_module)
File "/home/travis/odoo-9.0/openerp/modules/loading.py", line 305, in load_modules
modobj.button_install(cr, SUPERUSER_ID, ids)
File "/home/travis/odoo-9.0/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/home/travis/odoo-9.0/openerp/api.py", line 381, in old_api
result = method(recs, *args, **kwargs)
File "/home/travis/odoo-9.0/openerp/addons/base/module/module.py", line 414, in button_install
modules.state_update('to install', ['uninstalled'])
File "/home/travis/odoo-9.0/openerp/api.py", line 248, in wrapper
return new_api(self, *args, **kwargs)
File "/home/travis/odoo-9.0/openerp/addons/base/module/module.py", line 380, in state_update
raise UserError(_("You try to install module '%s' that depends on module '%s'.\nBut the latter module is not available in your system.") % (module.name, dep.name,))
UserError: (u"You try to install module 'website_sale_stock_control_global' that depends on module 'stock_available_global'.\nBut the latter module is not available in your system.", None)
2018-04-19 07:33:24,680 23353 CRITICAL openerp_test openerp.service.server: Failed to initialize database `openerp_test`.
Traceback (most recent call last):
File "/home/travis/odoo-9.0/openerp/service/server.py", line 897, in preload_registries
registry = RegistryManager.new(dbname, update_module=update_module)
File "/home/travis/odoo-9.0/openerp/modules/registry.py", line 386, in new
openerp.modules.load_modules(registry._db, force_demo, status, update_module)
File "/home/travis/odoo-9.0/openerp/modules/loading.py", line 305, in load_modules
modobj.button_install(cr, SUPERUSER_ID, ids)
File "/home/travis/odoo-9.0/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/home/travis/odoo-9.0/openerp/api.py", line 381, in old_api
result = method(recs, *args, **kwargs)
File "/home/travis/odoo-9.0/openerp/addons/base/module/module.py", line 414, in button_install
modules.state_update('to install', ['uninstalled'])
File "/home/travis/odoo-9.0/openerp/api.py", line 248, in wrapper
return new_api(self, *args, **kwargs)
File "/home/travis/odoo-9.0/openerp/addons/base/module/module.py", line 380, in state_update
raise UserError(_("You try to install module '%s' that depends on module '%s'.\nBut the latter module is not available in your system.") % (module.name, dep.name,))
UserError: (u"You try to install module 'website_sale_stock_control_global' that depends on module 'stock_available_global'.\nBut the latter module is not available in your system.", None)
```

**Comment by rafaelbn** [comment]
This module has been in production for 2 years! Let's go @sergio-teruel @pedrobaeza  :smile:

**Comment by yajo** [comment]
This is outdated, now in v11 only. v9 dependency was closed in https://github.com/OCA/stock-logistics-warehouse/pull/225. Closing too.

**Pull request closed without merging**
