### PR TITLE
[15.0] [MIG] website_sale_require_login: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36607

superseded from https://github.com/OCA/e-commerce/pull/618 as the author is giving no response.

This PR depends on:

- [x] https://github.com/OCA/e-commerce/pull/646

please @willytal @chienandalu review this.

### CODE REVIEW

**Review by BT-apadron — APPROVED** [review]
Approve!. Please propose this Pull Request in Migration to version 15.0 inside Issues.

**Review by chienandalu — APPROVED** [review]
Tested :+1:

**Pull request merged**
