### PR TITLE
[16.0][MIG] website_sale_tax_toggle: Migration to version 16.0

### PR DESCRIPTION
**Pull request by carlos-lopez-tecnativa**
@tecnativa  TT49822

### CODE REVIEW

**Comment by carlos-lopez-tecnativa** [comment]
@CarlosRoca13 @pedrobaeza @carolinafernandez-tecnativa could you please take a look

**Review by CarlosRoca13 — APPROVED** [review]
:+1:

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
