### PR TITLE
[IMP] Travis: Add website repo logic

### PR DESCRIPTION
**Pull request by lasley**
Do not merge until soon to be PR in MQT is merged & the branch is updated back to master

- [x] https://github.com/OCA/maintainer-quality-tools/pull/473
- [x] https://github.com/OCA/maintainer-quality-tools/pull/475

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Change now the branch.

**Comment by lasley** [comment]
MQT branch updated. IMO we should bypass approval for this & just merge assuming tests pass. I'll submit the v9 here in a sec

**Comment by pedrobaeza** [comment]
Runbot is failing with the same error as the other PR, so we should think there's something more.

**Comment by lasley** [comment]
> Runbot is failing with the same error as the other PR, so we should think there's something more.

This is an error in Runbot that used to happen to us quite often for numerous causes. In this case it looks like the [build wasn't even attempted](https://runbot2.odoo-community.org/runbot/static/build/3299841-194-fc375e/logs/job_00_prebuild.txt).

Typically an amend, push fixes. I'll try

**Comment by lasley** [comment]
Wait wtf our Runbot is linking to a prebuild log... This is the good one - https://runbot2.odoo-community.org/runbot/static/build/3299841-194-fc375e/logs/job_10_test_base.txt

```
[91m/home/odoo/maintainer-quality-tools/travis/travis_install_nightly: line 34: /home/odoo/.rvm/scripts/rvm: No such file or directory
[0mThe command '/bin/sh -c /bin/bash -c "source ${REPO_REQUIREMENTS}/virtualenv/python2.7/bin/activate && source ${REPO_REQUIREMENTS}/virtualenv/nodejs/bin/activate && source /rvm_env.sh && /before_install && /install"' returned a non-zero code: 1
```

**Comment by lasley** [comment]
@moylop260 - Do we have `rvm` on our Runbot image? This is where it starts getting into murky territory for me w/ the T2D implementation. Are we using [these images](https://github.com/Vauxoo/docker-odoo-image), with the suffixes representing the version numbers?

**Comment by yajo** [comment]
Dumb question: Why isn't ruby, sass and compass already included in the docker image?

**Comment by lasley** [comment]
We could include it in our's, but we're still left with it on Travis side. Rvm is installed on Travis though

**Comment by moylop260** [comment]
> Do we have `rvm` on our Runbot image? 

`docker run -it vauxoo/odoo-80-image-shippable-auto /usr/local/rvm/bin/rvm --version`
Result: `rvm 1.29.2 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]`

**Comment by yajo** [comment]
But Travis can run docker images, right?

**Comment by lasley** [comment]
Switched back to mainline MQT and rebuilding

**Pull request merged**
