### PR TITLE
[15.0][MIG] product_template_multi_link

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Standard migration 
CC @ForgeFlow

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
@OCA/e-commerce-maintainers ready to merge

**Comment by MiquelRForgeFlow** [comment]
Not sure if a rebase is needed for merge, as the copier template was updated a few days ago.

**Comment by MiquelRForgeFlow** [comment]
@e-commerce-maintainers please remove "stale" tag

**Comment by MiquelRForgeFlow** [comment]
@OCA/e-commerce-maintainers please remove "stale" tag

**Review by sbejaoui — APPROVED** [review]
LGTM, code review + functional test

**Review by lmignon — COMMENTED** [review]
LGTM, code review + functional test

**Review by lmignon — APPROVED** [review]
LGTM, code review + functional test

**Comment by HviorForgeFlow** [comment]
@pedrobaeza could we move it forward? Thanks in advice!

**Pull request merged**
