### PR TITLE
[14.0][MIG] website_sale_require_login: Migration to 14.0

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Comment by dsolanki-initos** [comment]
Hello,
Checks are not passed as website_sale_require_login is dependent upon module website_sale_suggestion_create_account.
Once branch (14.0-mig-website_sale_suggestion_create_account) containing this module (website_sale_suggestion_create_account) is merged with 14.0 branch then after check will be successfully passed.

**Comment by anajuaristi** [comment]
Hello!
Is this ready to be merged?

**Review by dsolanki-initos — APPROVED** [review]
LGTM. Code review and functional Tests.

**Comment by anajuaristi** [comment]
:+1: LGTM Functional tests

**Review by chienandalu — COMMENTED** [review]
Can you rebase @fshah-initos ?

**Review by houssine78 — APPROVED** [review]

**Comment by houssine78** [comment]
@fshah-initos you need to rebase

**Comment by dreispt** [comment]
Travis is red.

**Comment by josemonsalve2** [comment]
Hi, I was wondering. is there any reason why this has not been merged?

**Comment by pedrobaeza** [comment]
Starting with, CI is red, and a PSC review is always desired.

**Comment by josemonsalve2** [comment]
That makes sense. 

It seems like the error is the other module that hasn't been migrated: `website_sale_suggestion_create_account`. 

Is anyone working on migrating this other module? I've not migrated a module before, but I may be able to take a look. It did not seem that complicated.

**Comment by pedrobaeza** [comment]
It's a weird error. Maybe a rebase over current branch fixes it.

**Review by tarteo — CHANGES_REQUESTED** [review]
It should also 'block' _/shop/address_.  The checkout process works perfectly, but I can still enter `/shop/address` manually into the address bar and by-pass it.

```
    @http.route(auth="user")
    def address(self, **post):
        return super().address(**post)
```

**Pull request closed without merging**
