### PR TITLE
[16.0][MIG] website_sale_attribute_filter_multiselect: migration to 16.0

### PR DESCRIPTION
**Pull request by miguel-S73**
Standard migration from :
- https://github.com/OCA/e-commerce/pull/732

### CODE REVIEW

**Review by bizzappdev — APPROVED** [review]
LGTM

**Review by chienandalu — COMMENTED** [review]
Check pre-commit issues

**Comment by miguel-S73** [comment]
@chienandalu I have fixed pre-commit issue.
Thank you.

**Review by hildickethan — APPROVED** [review]

**Pull request merged**
