### PR TITLE
[14.0][MIG] website_sale_product_attachment: Migration to 14.0

### PR DESCRIPTION
**Pull request by miguel-S73**
reopen https://github.com/OCA/e-commerce/pull/559

Standard migration Odoo 14.0

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

**Review by geomer198 — APPROVED** [review]

**Comment by geomer198** [comment]
Code Review ok!

**Comment by francesco-ooops** [comment]
@OCA/e-commerce-maintainers good for merge?

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
