### PR TITLE
[FIX] website_sale_suggest_create_account: signup allowed detection

### LINKED ISSUE #412: [12.0][BUG][website_sale_suggest_create_account] 404: Page not found!
@Yajo @eLBati please

1. Go to runbot
2. Buy and press "Sign up and checkout"
3. You get a 404: Page not found! Here with this URL

http://3432322-12-0-004e2c.runbot2-3.odoo-community.org/web/signup?redirect=/shop/checkout?express=1

See:

website_sale_suggest_create_account

### PR DESCRIPTION
**Pull request by yajo**
Fix #412 by using the proper method to obtain signup invitation scope.

### CODE REVIEW

**Review by eLBati — APPROVED** [review]
LGTM, no test

**Review by pedrobaeza — APPROVED** [review]

**Comment by cvinh** [comment]
Hello, are you going to fix 13.0 branch too (if it's needed) ?

**Comment by yajo** [comment]
Yes, on my way.

**Comment by yajo** [comment]
Well, nope. It seems in v13 the patch is not needed.

**Pull request merged**
