### PR TITLE
[16.0][MIG] website_sale_product_description: Migration to 16.0

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Review by antoniocanovas — APPROVED** [review]
Functional review OK

**Review by Highcooley — APPROVED** [review]

**Comment by Highcooley** [comment]
Code review OK

**Comment by Highcooley** [comment]
Could I get some reviews for https://github.com/OCA/e-commerce/pull/785 in turn? Thanks ;-)

**Comment by JrAdhoc** [comment]
@pedrobaeza is this PR ready for merging?
Both functional and code reviews LGTM

**Pull request merged**
