### PR TITLE
[13.0][MIG] product_template_multi_link: Migration to 13.0

### PR DESCRIPTION
**Pull request by lmignon**

### CODE REVIEW

**Review by simahawk — APPROVED** [review]
@lmignon all the remarks I was about to post are already addressed in #316 :)
I think we can fast track this and focus on the refactoring.

**Comment by lmignon** [comment]
@simahawk We have to find someone with the super power to merge this one...

**Comment by simahawk** [comment]
@legalsylvain mind to have a look?

**Comment by simahawk** [comment]
@rousseldenis could you pass by for a review? :pray: 
@lmignon pre-commit updates to handled ;)

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@lmignon Could you fix conflict ?

**Comment by rousseldenis** [comment]
@lmignon

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍

**Comment by rousseldenis** [comment]
@lmignon Do you let commits as is or do you squash ?

**Comment by lmignon** [comment]
@rousseldenis As is plz :smirk:

**Comment by rousseldenis** [comment]
@OCA/e-commerce-maintainers

**Pull request merged**
