### PR TITLE
[FIX] website_sale_affiliate: correctly pass category and search para…

### LINKED ISSUE #296: [10.0][BUG] website_sale_affiliate : product controller hides category and search
The "product" controller calls super's product method with empty string as values for the "category" and "search" parameters instead of the values passed as arguments.

### PR DESCRIPTION
**Pull request by fcayre**
…meters to parent product controller

Fixes #296

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please rebase over current 10.0 branch, that I have fixed Travis status.

**Comment by fcayre** [comment]
Hello @pedrobaeza Travis is still failing, can you please fix this?

**Comment by fcayre** [comment]
Oups sorry @pedrobaeza you already did it without pinging me. I am rebasing again.

**Comment by fcayre** [comment]
@pedrobaeza more travis configuration errors to be fixed; thanks.

**Comment by fcayre** [comment]
@pedrobaeza I think I fixed travis conf issues but one test is still failing (TestUi.test_price_tiers in odoo.addons.website_sale_price_tier.tests.test_ui), which seems unrelated to my fix.

**Comment by pedrobaeza** [comment]
Indeed main branch is still red. I thought it was fixed. @sergio-teruel maybe you can give us a hand here.

**Pull request closed without merging**
