### PR TITLE
[15.0] [MIG] website_sale_product_attachment

### PR DESCRIPTION
**Pull request by angelgarciadelachica**

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@ValentinVinagre @HaraldPanten

**Review by luis-ron — APPROVED** [review]
Functional review, LGTM

**Review by HaraldPanten — APPROVED** [review]

**Comment by HaraldPanten** [comment]
@rafaelbn @simahawk is it ready to merge?

THX!

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by chienandalu — APPROVED** [review]
Code and functional review. Thanks!

**Pull request merged**
