### PR TITLE
[IMP] Travis: Add website repo logic

### PR DESCRIPTION
**Pull request by lasley**
Port of #194

### CODE REVIEW

**Comment by yajo** [comment]
Seems like https://github.com/OCA/maintainer-quality-tools/issues/471 [persists](https://github.com/OCA/maintainer-quality-tools/issues/471).

**Comment by yajo** [comment]
I just rebuilt and got the same sass problem. Any clues friend?

**Comment by pedrobaeza** [comment]
So we have it?

**Comment by lasley** [comment]
I don't think we had it with my 0055e82 commit - there were still some errors on Runbot side. I think Moises nailed it though - we'll see soon in  f3fc354

**Comment by moylop260** [comment]
I saw travis green and runbot green
How I can tested it functionality from runbot?

**Comment by lasley** [comment]
> I saw travis green and runbot green

The installs look to be a success too

> How I can tested it functionality from runbot?

I'm not sure on this one - I think the usability issues that were noticed were in the code of the modules, and not actually something our end. My head's spinning still from all the random issues though, so I could be 100% incorrect.

**Comment by lasley** [comment]
@pedrobaeza - when you mentioned that your colleague will be out of town for a week, is this Jairo you are speaking of?

**Comment by moylop260** [comment]
Well, I will run the tests from runbot with ssh access

**Comment by moylop260** [comment]
Using the build https://runbot.odoo-community.org/runbot/build/3300619 running:
`~/odoo-9.0/odoo.py --xmlrpc-port=18069 -d openerp_test --db-filter=openerp_test -u website_sale_qty,website_sale_default_country,website_sale_product_brand,product_multi_link,website_sale_require_login,website_sale_wishlist,website_sale_vat_required,website_sale_suggest_create_account,website_sale_checkout_country_vat,website_sale_require_legal --test-enable --stop-after-init` the result was successfully!:

 - screen shot 2017-08-11 at 13 46 21

**Comment by pedrobaeza** [comment]
Yes, it's Jairo who is in holidays. On runbot, just trying to login you find the problem.

**Review by moylop260 — APPROVED** [review]

**Pull request merged**
