### PR TITLE
[FIX][13.0]website_sale_product_detail_attribute_image rename file

### PR DESCRIPTION
**Pull request by emagdalenaC2i**
See #381 and #382
@pedrobaeza please, could you fast-tracking this PR?

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
@OCA/community-maintainers please, could check this PR?

**Comment by pedrobaeza** [comment]
Please squash commits into one.

**Comment by emagdalenaC2i** [comment]
I can't
I did it on Github website because I am using windows and I can't clone this repo with this filename.
And I can't rename that file on Github website.

**Comment by emagdalenaC2i** [comment]
@pedrobaeza done

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
